/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using bwdk_sdk.Api;
using bwdk_sdk.Model;

namespace bwdk_sdk.Client
{
    /// <summary>
    /// Provides hosting configuration for bwdk_sdk
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new AuthStatusResponseJsonConverter());
            _jsonOptions.Converters.Add(new BusinessAddressJsonConverter());
            _jsonOptions.Converters.Add(new DeliveryTimeRangeDisplayJsonConverter());
            _jsonOptions.Converters.Add(new ErrorEnumJsonConverter());
            _jsonOptions.Converters.Add(new ErrorEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new GatewayTypeEnumJsonConverter());
            _jsonOptions.Converters.Add(new GatewayTypeEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new MerchantJsonConverter());
            _jsonOptions.Converters.Add(new MerchantOrderCancelShipmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new MerchantOrderRefundResponseJsonConverter());
            _jsonOptions.Converters.Add(new MerchantOrderReviveShipmentResponseJsonConverter());
            _jsonOptions.Converters.Add(new MerchantPaidOrderListJsonConverter());
            _jsonOptions.Converters.Add(new NullEnumJsonConverter());
            _jsonOptions.Converters.Add(new NullEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new OptionJsonConverter());
            _jsonOptions.Converters.Add(new OrderCreateJsonConverter());
            _jsonOptions.Converters.Add(new OrderCreateResponseJsonConverter());
            _jsonOptions.Converters.Add(new OrderDetailJsonConverter());
            _jsonOptions.Converters.Add(new OrderErrorJsonConverter());
            _jsonOptions.Converters.Add(new OrderItemCreateJsonConverter());
            _jsonOptions.Converters.Add(new OrderStatusEnumJsonConverter());
            _jsonOptions.Converters.Add(new OrderStatusEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new OrderUserJsonConverter());
            _jsonOptions.Converters.Add(new PackingJsonConverter());
            _jsonOptions.Converters.Add(new PaginatedMerchantPaidOrderListListJsonConverter());
            _jsonOptions.Converters.Add(new PaginatedOrderDetailListJsonConverter());
            _jsonOptions.Converters.Add(new PaymentOrderJsonConverter());
            _jsonOptions.Converters.Add(new RefundOrderJsonConverter());
            _jsonOptions.Converters.Add(new ReviveShipmentJsonConverter());
            _jsonOptions.Converters.Add(new ShippingMethodJsonConverter());
            _jsonOptions.Converters.Add(new ShippingTypeEnumJsonConverter());
            _jsonOptions.Converters.Add(new ShippingTypeEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new TypeNameEnumJsonConverter());
            _jsonOptions.Converters.Add(new TypeNameEnumNullableJsonConverter());
            _jsonOptions.Converters.Add(new UpdateOrderStatusJsonConverter());
            _jsonOptions.Converters.Add(new VerifyOrderJsonConverter());
            _jsonOptions.Converters.Add(new WalletBalanceJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<MerchantOrdersApiEvents>();
            _services.AddSingleton<MerchantWalletApiEvents>();
            _services.AddSingleton<OrderShippingApiEvents>();
            _services.AddSingleton<SellerProfileManagementApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IMerchantOrdersApi, MerchantOrdersApi>("bwdk_sdk.Api.IMerchantOrdersApi", client));
            builders.Add(_services.AddHttpClient<IMerchantWalletApi, MerchantWalletApi>("bwdk_sdk.Api.IMerchantWalletApi", client));
            builders.Add(_services.AddHttpClient<IOrderShippingApi, OrderShippingApi>("bwdk_sdk.Api.IOrderShippingApi", client));
            builders.Add(_services.AddHttpClient<ISellerProfileManagementApi, SellerProfileManagementApi>("bwdk_sdk.Api.ISellerProfileManagementApi", client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
