/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using bwdk_sdk.Api;
using bwdk_sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace bwdk_sdk.Test.Api
{
    /// <summary>
    ///  Class for testing MerchantOrdersApi
    /// </summary>
    public sealed class MerchantOrdersApiTests : ApiTestsBase
    {
        private readonly IMerchantOrdersApi _instance;

        public MerchantOrdersApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IMerchantOrdersApi>();
        }

        /// <summary>
        /// Test OrderApiV1CreateOrderCreate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1CreateOrderCreateAsyncTest()
        {
            OrderCreate orderCreate = default!;
            var response = await _instance.OrderApiV1CreateOrderCreateAsync(orderCreate);
            var model = response.Created();
            Assert.IsType<OrderCreateResponse>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerListAsyncTest()
        {
            Client.Option<string> cities = default!;
            Client.Option<DateOnly> createdAt = default!;
            Client.Option<string> cursor = default!;
            Client.Option<string> orderIds = default!;
            Client.Option<string> ordering = default!;
            Client.Option<string> paymentTypes = default!;
            Client.Option<string> provinces = default!;
            Client.Option<string> referenceCode = default!;
            Client.Option<string> search = default!;
            Client.Option<string> shippingTypes = default!;
            Client.Option<int> status = default!;
            Client.Option<string> statuses = default!;
            Client.Option<bool> todayPickup = default!;
            var response = await _instance.OrderApiV1ManagerListAsync(cities, createdAt, cursor, orderIds, ordering, paymentTypes, provinces, referenceCode, search, shippingTypes, status, statuses, todayPickup);
            var model = response.Ok();
            Assert.IsType<PaginatedOrderDetailList>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerPaidList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerPaidListAsyncTest()
        {
            Client.Option<string> cities = default!;
            Client.Option<DateOnly> createdAt = default!;
            Client.Option<string> cursor = default!;
            Client.Option<string> orderIds = default!;
            Client.Option<string> ordering = default!;
            Client.Option<string> paymentTypes = default!;
            Client.Option<string> provinces = default!;
            Client.Option<string> referenceCode = default!;
            Client.Option<string> search = default!;
            Client.Option<string> shippingTypes = default!;
            Client.Option<int> status = default!;
            Client.Option<string> statuses = default!;
            Client.Option<bool> todayPickup = default!;
            var response = await _instance.OrderApiV1ManagerPaidListAsync(cities, createdAt, cursor, orderIds, ordering, paymentTypes, provinces, referenceCode, search, shippingTypes, status, statuses, todayPickup);
            var model = response.Ok();
            Assert.IsType<PaginatedMerchantPaidOrderListList>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerRefundCreate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerRefundCreateAsyncTest()
        {
            Guid orderUuid = default!;
            Client.Option<RefundOrder> refundOrder = default!;
            var response = await _instance.OrderApiV1ManagerRefundCreateAsync(orderUuid, refundOrder);
            var model = response.Ok();
            Assert.IsType<MerchantOrderRefundResponse>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerRetrieve
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerRetrieveAsyncTest()
        {
            Guid orderUuid = default!;
            var response = await _instance.OrderApiV1ManagerRetrieveAsync(orderUuid);
            var model = response.Ok();
            Assert.IsType<OrderDetail>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerUpdateStatusUpdate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerUpdateStatusUpdateAsyncTest()
        {
            Guid orderUuid = default!;
            UpdateOrderStatus updateOrderStatus = default!;
            var response = await _instance.OrderApiV1ManagerUpdateStatusUpdateAsync(orderUuid, updateOrderStatus);
            var model = response.Ok();
            Assert.IsType<OrderDetail>(model);
        }

        /// <summary>
        /// Test OrderApiV1ManagerVerifyCreate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task OrderApiV1ManagerVerifyCreateAsyncTest()
        {
            Guid orderUuid = default!;
            VerifyOrder verifyOrder = default!;
            var response = await _instance.OrderApiV1ManagerVerifyCreateAsync(orderUuid, verifyOrder);
            var model = response.Ok();
            Assert.IsType<OrderDetail>(model);
        }
    }
}
