/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using bwdk_sdk.Api;
using bwdk_sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace bwdk_sdk.Test.Api
{
    /// <summary>
    ///  Class for testing SellerProfileManagementApi
    /// </summary>
    public sealed class SellerProfileManagementApiTests : ApiTestsBase
    {
        private readonly ISellerProfileManagementApi _instance;

        public SellerProfileManagementApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ISellerProfileManagementApi>();
        }

        /// <summary>
        /// Test MerchantApiV1AuthStatusRetrieve
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task MerchantApiV1AuthStatusRetrieveAsyncTest()
        {
            var response = await _instance.MerchantApiV1AuthStatusRetrieveAsync();
            var model = response.Ok();
            Assert.IsType<AuthStatusResponse>(model);
        }
    }
}
