/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing BusinessAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BusinessAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BusinessAddress
        //private BusinessAddress instance;

        public BusinessAddressTests()
        {
            // TODO uncomment below to create an instance of BusinessAddress
            //instance = new BusinessAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BusinessAddress
        /// </summary>
        [Fact]
        public void BusinessAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" BusinessAddress
            //Assert.IsType<BusinessAddress>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Fact]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }

        /// <summary>
        /// Test the property 'StateName'
        /// </summary>
        [Fact]
        public void StateNameTest()
        {
            // TODO unit test for the property 'StateName'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'ModifiedAt'
        /// </summary>
        [Fact]
        public void ModifiedAtTest()
        {
            // TODO unit test for the property 'ModifiedAt'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'DistrictId'
        /// </summary>
        [Fact]
        public void DistrictIdTest()
        {
            // TODO unit test for the property 'DistrictId'
        }

        /// <summary>
        /// Test the property 'DistrictName'
        /// </summary>
        [Fact]
        public void DistrictNameTest()
        {
            // TODO unit test for the property 'DistrictName'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'BuildingNumber'
        /// </summary>
        [Fact]
        public void BuildingNumberTest()
        {
            // TODO unit test for the property 'BuildingNumber'
        }

        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Fact]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }

        /// <summary>
        /// Test the property 'ReceiverName'
        /// </summary>
        [Fact]
        public void ReceiverNameTest()
        {
            // TODO unit test for the property 'ReceiverName'
        }

        /// <summary>
        /// Test the property 'ReceiverPhone'
        /// </summary>
        [Fact]
        public void ReceiverPhoneTest()
        {
            // TODO unit test for the property 'ReceiverPhone'
        }

        /// <summary>
        /// Test the property 'IsAccurate'
        /// </summary>
        [Fact]
        public void IsAccurateTest()
        {
            // TODO unit test for the property 'IsAccurate'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
    }
}
