/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing MerchantOrderRefundResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantOrderRefundResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantOrderRefundResponse
        //private MerchantOrderRefundResponse instance;

        public MerchantOrderRefundResponseTests()
        {
            // TODO uncomment below to create an instance of MerchantOrderRefundResponse
            //instance = new MerchantOrderRefundResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantOrderRefundResponse
        /// </summary>
        [Fact]
        public void MerchantOrderRefundResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" MerchantOrderRefundResponse
            //Assert.IsType<MerchantOrderRefundResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'OrderUuid'
        /// </summary>
        [Fact]
        public void OrderUuidTest()
        {
            // TODO unit test for the property 'OrderUuid'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusDisplay'
        /// </summary>
        [Fact]
        public void StatusDisplayTest()
        {
            // TODO unit test for the property 'StatusDisplay'
        }

        /// <summary>
        /// Test the property 'RefundReason'
        /// </summary>
        [Fact]
        public void RefundReasonTest()
        {
            // TODO unit test for the property 'RefundReason'
        }
    }
}
