/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing OrderUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderUser
        //private OrderUser instance;

        public OrderUserTests()
        {
            // TODO uncomment below to create an instance of OrderUser
            //instance = new OrderUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderUser
        /// </summary>
        [Fact]
        public void OrderUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderUser
            //Assert.IsType<OrderUser>(instance);
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }

        /// <summary>
        /// Test the property 'NationalIdentityNumber'
        /// </summary>
        [Fact]
        public void NationalIdentityNumberTest()
        {
            // TODO unit test for the property 'NationalIdentityNumber'
        }

        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
    }
}
