/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing PaginatedMerchantPaidOrderListList
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginatedMerchantPaidOrderListListTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginatedMerchantPaidOrderListList
        //private PaginatedMerchantPaidOrderListList instance;

        public PaginatedMerchantPaidOrderListListTests()
        {
            // TODO uncomment below to create an instance of PaginatedMerchantPaidOrderListList
            //instance = new PaginatedMerchantPaidOrderListList();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginatedMerchantPaidOrderListList
        /// </summary>
        [Fact]
        public void PaginatedMerchantPaidOrderListListInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginatedMerchantPaidOrderListList
            //Assert.IsType<PaginatedMerchantPaidOrderListList>(instance);
        }

        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Fact]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

        /// <summary>
        /// Test the property 'Next'
        /// </summary>
        [Fact]
        public void NextTest()
        {
            // TODO unit test for the property 'Next'
        }

        /// <summary>
        /// Test the property 'Previous'
        /// </summary>
        [Fact]
        public void PreviousTest()
        {
            // TODO unit test for the property 'Previous'
        }
    }
}
