/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing ShippingMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShippingMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShippingMethod
        //private ShippingMethod instance;

        public ShippingMethodTests()
        {
            // TODO uncomment below to create an instance of ShippingMethod
            //instance = new ShippingMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShippingMethod
        /// </summary>
        [Fact]
        public void ShippingMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShippingMethod
            //Assert.IsType<ShippingMethod>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'GetShippingTypeDisplay'
        /// </summary>
        [Fact]
        public void GetShippingTypeDisplayTest()
        {
            // TODO unit test for the property 'GetShippingTypeDisplay'
        }

        /// <summary>
        /// Test the property 'ShippingTypeDisplay'
        /// </summary>
        [Fact]
        public void ShippingTypeDisplayTest()
        {
            // TODO unit test for the property 'ShippingTypeDisplay'
        }

        /// <summary>
        /// Test the property 'DeliveryTimeDisplay'
        /// </summary>
        [Fact]
        public void DeliveryTimeDisplayTest()
        {
            // TODO unit test for the property 'DeliveryTimeDisplay'
        }

        /// <summary>
        /// Test the property 'DeliveryTimeRangeDisplay'
        /// </summary>
        [Fact]
        public void DeliveryTimeRangeDisplayTest()
        {
            // TODO unit test for the property 'DeliveryTimeRangeDisplay'
        }

        /// <summary>
        /// Test the property 'InventoryAddress'
        /// </summary>
        [Fact]
        public void InventoryAddressTest()
        {
            // TODO unit test for the property 'InventoryAddress'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ShippingType'
        /// </summary>
        [Fact]
        public void ShippingTypeTest()
        {
            // TODO unit test for the property 'ShippingType'
        }

        /// <summary>
        /// Test the property 'Cost'
        /// </summary>
        [Fact]
        public void CostTest()
        {
            // TODO unit test for the property 'Cost'
        }

        /// <summary>
        /// Test the property 'SecondaryCost'
        /// </summary>
        [Fact]
        public void SecondaryCostTest()
        {
            // TODO unit test for the property 'SecondaryCost'
        }

        /// <summary>
        /// Test the property 'MinimumTimeSending'
        /// </summary>
        [Fact]
        public void MinimumTimeSendingTest()
        {
            // TODO unit test for the property 'MinimumTimeSending'
        }

        /// <summary>
        /// Test the property 'MaximumTimeSending'
        /// </summary>
        [Fact]
        public void MaximumTimeSendingTest()
        {
            // TODO unit test for the property 'MaximumTimeSending'
        }

        /// <summary>
        /// Test the property 'IsPayAtDestination'
        /// </summary>
        [Fact]
        public void IsPayAtDestinationTest()
        {
            // TODO unit test for the property 'IsPayAtDestination'
        }
    }
}
