/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using bwdk_sdk.Model;
using bwdk_sdk.Client;
using System.Reflection;

namespace bwdk_sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateOrderStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateOrderStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateOrderStatus
        //private UpdateOrderStatus instance;

        public UpdateOrderStatusTests()
        {
            // TODO uncomment below to create an instance of UpdateOrderStatus
            //instance = new UpdateOrderStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateOrderStatus
        /// </summary>
        [Fact]
        public void UpdateOrderStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateOrderStatus
            //Assert.IsType<UpdateOrderStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
