// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// * &#x60;User is not authenticated.&#x60; - کاربر تأیید هویت نشده است. * &#x60;Order not found.&#x60; - Order not found. * &#x60;Order is not in a state where shipping can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * &#x60;Order is not in a state where packing can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * &#x60;Failed to initiate refund. Please try again later.&#x60; - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * &#x60;Order is expired or cancelled.&#x60; - سفارش منقضی‌شده یا لغو‌شده است. * &#x60;Invalid request origin.&#x60; - Invalid request origin. * &#x60;Digi Express shipping method not found.&#x60; - روش ارسال دیجی اکسپرس یافت نشد. * &#x60;Order address not found.&#x60; - آدرس سفارش یافت نشد. * &#x60;Failed to fetch Digi Express shipping time window options.&#x60; - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * &#x60;Address ID not found.&#x60; - Address ID not found. * &#x60;Failed to cancel shipment.&#x60; - خطا در کنسل کردن مرسوله. * &#x60;Failed to cancel shipment in third party service.&#x60; - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * &#x60;Shipment not found.&#x60; - Shipment not found. * &#x60;Selected shipping method is not eligible for cancellation.&#x60; - Selected shipping method is not eligible for cancellation. * &#x60;DigiExpress shipment is not in cancelable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * &#x60;DigiExpress shipment is not in reviveable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * &#x60;Failed to revive shipment in third party service.&#x60; - Failed to revive shipment in third party service. * &#x60;Selected shipping method is not eligible for revival.&#x60; - Selected shipping method is not eligible for revival.
    /// </summary>
    /// <value>* &#x60;User is not authenticated.&#x60; - کاربر تأیید هویت نشده است. * &#x60;Order not found.&#x60; - Order not found. * &#x60;Order is not in a state where shipping can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان روش ارسال را انتخاب کرد. * &#x60;Order is not in a state where packing can be selected.&#x60; - سفارش در وضعیتی نیست که بتوان بسته‌بندی را انتخاب کرد. * &#x60;Failed to initiate refund. Please try again later.&#x60; - عملیات بازپرداخت ناموفق بود. لطفاً بعداً دوباره امتحان کنید. * &#x60;Order is expired or cancelled.&#x60; - سفارش منقضی‌شده یا لغو‌شده است. * &#x60;Invalid request origin.&#x60; - Invalid request origin. * &#x60;Digi Express shipping method not found.&#x60; - روش ارسال دیجی اکسپرس یافت نشد. * &#x60;Order address not found.&#x60; - آدرس سفارش یافت نشد. * &#x60;Failed to fetch Digi Express shipping time window options.&#x60; - دریافت گزینه‌های بازه زمانی ارسال دیجی اکسپرس ناموفق بود. * &#x60;Address ID not found.&#x60; - Address ID not found. * &#x60;Failed to cancel shipment.&#x60; - خطا در کنسل کردن مرسوله. * &#x60;Failed to cancel shipment in third party service.&#x60; - خطا در کنسل کردن مرسوله از سمت سرویس خارجی. * &#x60;Shipment not found.&#x60; - Shipment not found. * &#x60;Selected shipping method is not eligible for cancellation.&#x60; - Selected shipping method is not eligible for cancellation. * &#x60;DigiExpress shipment is not in cancelable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل کنسل شدن نیست. * &#x60;DigiExpress shipment is not in reviveable in this state&#x60; - مرسوله دیجی‌اکسپرس در این وضعیت قابل ارسال مجدد نیست. * &#x60;Failed to revive shipment in third party service.&#x60; - Failed to revive shipment in third party service. * &#x60;Selected shipping method is not eligible for revival.&#x60; - Selected shipping method is not eligible for revival.</value>
    public enum ErrorEnum
    {
        /// <summary>
        /// Enum UserIsNotAuthenticated for value: User is not authenticated.
        /// </summary>
        UserIsNotAuthenticated = 1,

        /// <summary>
        /// Enum OrderNotFound for value: Order not found.
        /// </summary>
        OrderNotFound = 2,

        /// <summary>
        /// Enum OrderIsNotInAStateWhereShippingCanBeSelected for value: Order is not in a state where shipping can be selected.
        /// </summary>
        OrderIsNotInAStateWhereShippingCanBeSelected = 3,

        /// <summary>
        /// Enum OrderIsNotInAStateWherePackingCanBeSelected for value: Order is not in a state where packing can be selected.
        /// </summary>
        OrderIsNotInAStateWherePackingCanBeSelected = 4,

        /// <summary>
        /// Enum FailedToInitiateRefundPleaseTryAgainLater for value: Failed to initiate refund. Please try again later.
        /// </summary>
        FailedToInitiateRefundPleaseTryAgainLater = 5,

        /// <summary>
        /// Enum OrderIsExpiredOrCancelled for value: Order is expired or cancelled.
        /// </summary>
        OrderIsExpiredOrCancelled = 6,

        /// <summary>
        /// Enum InvalidRequestOrigin for value: Invalid request origin.
        /// </summary>
        InvalidRequestOrigin = 7,

        /// <summary>
        /// Enum DigiExpressShippingMethodNotFound for value: Digi Express shipping method not found.
        /// </summary>
        DigiExpressShippingMethodNotFound = 8,

        /// <summary>
        /// Enum OrderAddressNotFound for value: Order address not found.
        /// </summary>
        OrderAddressNotFound = 9,

        /// <summary>
        /// Enum FailedToFetchDigiExpressShippingTimeWindowOptions for value: Failed to fetch Digi Express shipping time window options.
        /// </summary>
        FailedToFetchDigiExpressShippingTimeWindowOptions = 10,

        /// <summary>
        /// Enum AddressIDNotFound for value: Address ID not found.
        /// </summary>
        AddressIDNotFound = 11,

        /// <summary>
        /// Enum FailedToCancelShipment for value: Failed to cancel shipment.
        /// </summary>
        FailedToCancelShipment = 12,

        /// <summary>
        /// Enum FailedToCancelShipmentInThirdPartyService for value: Failed to cancel shipment in third party service.
        /// </summary>
        FailedToCancelShipmentInThirdPartyService = 13,

        /// <summary>
        /// Enum ShipmentNotFound for value: Shipment not found.
        /// </summary>
        ShipmentNotFound = 14,

        /// <summary>
        /// Enum SelectedShippingMethodIsNotEligibleForCancellation for value: Selected shipping method is not eligible for cancellation.
        /// </summary>
        SelectedShippingMethodIsNotEligibleForCancellation = 15,

        /// <summary>
        /// Enum DigiExpressShipmentIsNotInCancelableInThisState for value: DigiExpress shipment is not in cancelable in this state
        /// </summary>
        DigiExpressShipmentIsNotInCancelableInThisState = 16,

        /// <summary>
        /// Enum DigiExpressShipmentIsNotInReviveableInThisState for value: DigiExpress shipment is not in reviveable in this state
        /// </summary>
        DigiExpressShipmentIsNotInReviveableInThisState = 17,

        /// <summary>
        /// Enum FailedToReviveShipmentInThirdPartyService for value: Failed to revive shipment in third party service.
        /// </summary>
        FailedToReviveShipmentInThirdPartyService = 18,

        /// <summary>
        /// Enum SelectedShippingMethodIsNotEligibleForRevival for value: Selected shipping method is not eligible for revival.
        /// </summary>
        SelectedShippingMethodIsNotEligibleForRevival = 19
    }

    /// <summary>
    /// Converts <see cref="ErrorEnum"/> to and from the JSON value
    /// </summary>
    public static class ErrorEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="ErrorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ErrorEnum FromString(string value)
        {
            if (value.Equals("User is not authenticated."))
                return ErrorEnum.UserIsNotAuthenticated;

            if (value.Equals("Order not found."))
                return ErrorEnum.OrderNotFound;

            if (value.Equals("Order is not in a state where shipping can be selected."))
                return ErrorEnum.OrderIsNotInAStateWhereShippingCanBeSelected;

            if (value.Equals("Order is not in a state where packing can be selected."))
                return ErrorEnum.OrderIsNotInAStateWherePackingCanBeSelected;

            if (value.Equals("Failed to initiate refund. Please try again later."))
                return ErrorEnum.FailedToInitiateRefundPleaseTryAgainLater;

            if (value.Equals("Order is expired or cancelled."))
                return ErrorEnum.OrderIsExpiredOrCancelled;

            if (value.Equals("Invalid request origin."))
                return ErrorEnum.InvalidRequestOrigin;

            if (value.Equals("Digi Express shipping method not found."))
                return ErrorEnum.DigiExpressShippingMethodNotFound;

            if (value.Equals("Order address not found."))
                return ErrorEnum.OrderAddressNotFound;

            if (value.Equals("Failed to fetch Digi Express shipping time window options."))
                return ErrorEnum.FailedToFetchDigiExpressShippingTimeWindowOptions;

            if (value.Equals("Address ID not found."))
                return ErrorEnum.AddressIDNotFound;

            if (value.Equals("Failed to cancel shipment."))
                return ErrorEnum.FailedToCancelShipment;

            if (value.Equals("Failed to cancel shipment in third party service."))
                return ErrorEnum.FailedToCancelShipmentInThirdPartyService;

            if (value.Equals("Shipment not found."))
                return ErrorEnum.ShipmentNotFound;

            if (value.Equals("Selected shipping method is not eligible for cancellation."))
                return ErrorEnum.SelectedShippingMethodIsNotEligibleForCancellation;

            if (value.Equals("DigiExpress shipment is not in cancelable in this state"))
                return ErrorEnum.DigiExpressShipmentIsNotInCancelableInThisState;

            if (value.Equals("DigiExpress shipment is not in reviveable in this state"))
                return ErrorEnum.DigiExpressShipmentIsNotInReviveableInThisState;

            if (value.Equals("Failed to revive shipment in third party service."))
                return ErrorEnum.FailedToReviveShipmentInThirdPartyService;

            if (value.Equals("Selected shipping method is not eligible for revival."))
                return ErrorEnum.SelectedShippingMethodIsNotEligibleForRevival;

            throw new NotImplementedException($"Could not convert value to type ErrorEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="ErrorEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static ErrorEnum? FromStringOrDefault(string value)
        {
            if (value.Equals("User is not authenticated."))
                return ErrorEnum.UserIsNotAuthenticated;

            if (value.Equals("Order not found."))
                return ErrorEnum.OrderNotFound;

            if (value.Equals("Order is not in a state where shipping can be selected."))
                return ErrorEnum.OrderIsNotInAStateWhereShippingCanBeSelected;

            if (value.Equals("Order is not in a state where packing can be selected."))
                return ErrorEnum.OrderIsNotInAStateWherePackingCanBeSelected;

            if (value.Equals("Failed to initiate refund. Please try again later."))
                return ErrorEnum.FailedToInitiateRefundPleaseTryAgainLater;

            if (value.Equals("Order is expired or cancelled."))
                return ErrorEnum.OrderIsExpiredOrCancelled;

            if (value.Equals("Invalid request origin."))
                return ErrorEnum.InvalidRequestOrigin;

            if (value.Equals("Digi Express shipping method not found."))
                return ErrorEnum.DigiExpressShippingMethodNotFound;

            if (value.Equals("Order address not found."))
                return ErrorEnum.OrderAddressNotFound;

            if (value.Equals("Failed to fetch Digi Express shipping time window options."))
                return ErrorEnum.FailedToFetchDigiExpressShippingTimeWindowOptions;

            if (value.Equals("Address ID not found."))
                return ErrorEnum.AddressIDNotFound;

            if (value.Equals("Failed to cancel shipment."))
                return ErrorEnum.FailedToCancelShipment;

            if (value.Equals("Failed to cancel shipment in third party service."))
                return ErrorEnum.FailedToCancelShipmentInThirdPartyService;

            if (value.Equals("Shipment not found."))
                return ErrorEnum.ShipmentNotFound;

            if (value.Equals("Selected shipping method is not eligible for cancellation."))
                return ErrorEnum.SelectedShippingMethodIsNotEligibleForCancellation;

            if (value.Equals("DigiExpress shipment is not in cancelable in this state"))
                return ErrorEnum.DigiExpressShipmentIsNotInCancelableInThisState;

            if (value.Equals("DigiExpress shipment is not in reviveable in this state"))
                return ErrorEnum.DigiExpressShipmentIsNotInReviveableInThisState;

            if (value.Equals("Failed to revive shipment in third party service."))
                return ErrorEnum.FailedToReviveShipmentInThirdPartyService;

            if (value.Equals("Selected shipping method is not eligible for revival."))
                return ErrorEnum.SelectedShippingMethodIsNotEligibleForRevival;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="ErrorEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static string ToJsonValue(ErrorEnum value)
        {
            if (value == ErrorEnum.UserIsNotAuthenticated)
                return "User is not authenticated.";

            if (value == ErrorEnum.OrderNotFound)
                return "Order not found.";

            if (value == ErrorEnum.OrderIsNotInAStateWhereShippingCanBeSelected)
                return "Order is not in a state where shipping can be selected.";

            if (value == ErrorEnum.OrderIsNotInAStateWherePackingCanBeSelected)
                return "Order is not in a state where packing can be selected.";

            if (value == ErrorEnum.FailedToInitiateRefundPleaseTryAgainLater)
                return "Failed to initiate refund. Please try again later.";

            if (value == ErrorEnum.OrderIsExpiredOrCancelled)
                return "Order is expired or cancelled.";

            if (value == ErrorEnum.InvalidRequestOrigin)
                return "Invalid request origin.";

            if (value == ErrorEnum.DigiExpressShippingMethodNotFound)
                return "Digi Express shipping method not found.";

            if (value == ErrorEnum.OrderAddressNotFound)
                return "Order address not found.";

            if (value == ErrorEnum.FailedToFetchDigiExpressShippingTimeWindowOptions)
                return "Failed to fetch Digi Express shipping time window options.";

            if (value == ErrorEnum.AddressIDNotFound)
                return "Address ID not found.";

            if (value == ErrorEnum.FailedToCancelShipment)
                return "Failed to cancel shipment.";

            if (value == ErrorEnum.FailedToCancelShipmentInThirdPartyService)
                return "Failed to cancel shipment in third party service.";

            if (value == ErrorEnum.ShipmentNotFound)
                return "Shipment not found.";

            if (value == ErrorEnum.SelectedShippingMethodIsNotEligibleForCancellation)
                return "Selected shipping method is not eligible for cancellation.";

            if (value == ErrorEnum.DigiExpressShipmentIsNotInCancelableInThisState)
                return "DigiExpress shipment is not in cancelable in this state";

            if (value == ErrorEnum.DigiExpressShipmentIsNotInReviveableInThisState)
                return "DigiExpress shipment is not in reviveable in this state";

            if (value == ErrorEnum.FailedToReviveShipmentInThirdPartyService)
                return "Failed to revive shipment in third party service.";

            if (value == ErrorEnum.SelectedShippingMethodIsNotEligibleForRevival)
                return "Selected shipping method is not eligible for revival.";

            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ErrorEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class ErrorEnumJsonConverter : JsonConverter<ErrorEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ErrorEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ErrorEnum? result = rawValue == null
                ? null
                : ErrorEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ErrorEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ErrorEnum errorEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(ErrorEnumValueConverter.ToJsonValue(errorEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ErrorEnum"/>
    /// </summary>
    public class ErrorEnumNullableJsonConverter : JsonConverter<ErrorEnum?>
    {
        /// <summary>
        /// Returns a ErrorEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override ErrorEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            ErrorEnum? result = rawValue == null
                ? null
                : ErrorEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the ErrorEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="errorEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, ErrorEnum? errorEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(errorEnum.HasValue ? ErrorEnumValueConverter.ToJsonValue(errorEnum.Value).ToString() : "null");
        }
    }
}
