// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// * &#x60;1&#x60; - آنلاین * &#x60;2&#x60; - BNPL (الان بخر، بعداً پرداخت کن) * &#x60;3&#x60; - اعتباری * &#x60;4&#x60; - کیف پول دیجی‌پی * &#x60;5&#x60; - اقساط پیش‌فرض
    /// </summary>
    /// <value>* &#x60;1&#x60; - آنلاین * &#x60;2&#x60; - BNPL (الان بخر، بعداً پرداخت کن) * &#x60;3&#x60; - اعتباری * &#x60;4&#x60; - کیف پول دیجی‌پی * &#x60;5&#x60; - اقساط پیش‌فرض</value>
    public enum GatewayTypeEnum
    {
        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5
    }

    /// <summary>
    /// Converts <see cref="GatewayTypeEnum"/> to and from the JSON value
    /// </summary>
    public static class GatewayTypeEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="GatewayTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GatewayTypeEnum FromString(string value)
        {
            if (value.Equals((1).ToString()))
                return GatewayTypeEnum.NUMBER_1;

            if (value.Equals((2).ToString()))
                return GatewayTypeEnum.NUMBER_2;

            if (value.Equals((3).ToString()))
                return GatewayTypeEnum.NUMBER_3;

            if (value.Equals((4).ToString()))
                return GatewayTypeEnum.NUMBER_4;

            if (value.Equals((5).ToString()))
                return GatewayTypeEnum.NUMBER_5;

            throw new NotImplementedException($"Could not convert value to type GatewayTypeEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="GatewayTypeEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static GatewayTypeEnum? FromStringOrDefault(string value)
        {
            if (value.Equals((1).ToString()))
                return GatewayTypeEnum.NUMBER_1;

            if (value.Equals((2).ToString()))
                return GatewayTypeEnum.NUMBER_2;

            if (value.Equals((3).ToString()))
                return GatewayTypeEnum.NUMBER_3;

            if (value.Equals((4).ToString()))
                return GatewayTypeEnum.NUMBER_4;

            if (value.Equals((5).ToString()))
                return GatewayTypeEnum.NUMBER_5;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="GatewayTypeEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(GatewayTypeEnum value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GatewayTypeEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class GatewayTypeEnumJsonConverter : JsonConverter<GatewayTypeEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override GatewayTypeEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            GatewayTypeEnum? result = rawValue == null
                ? null
                : GatewayTypeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the GatewayTypeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="gatewayTypeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, GatewayTypeEnum gatewayTypeEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(GatewayTypeEnumValueConverter.ToJsonValue(gatewayTypeEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GatewayTypeEnum"/>
    /// </summary>
    public class GatewayTypeEnumNullableJsonConverter : JsonConverter<GatewayTypeEnum?>
    {
        /// <summary>
        /// Returns a GatewayTypeEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override GatewayTypeEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            GatewayTypeEnum? result = rawValue == null
                ? null
                : GatewayTypeEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the GatewayTypeEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="gatewayTypeEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, GatewayTypeEnum? gatewayTypeEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(gatewayTypeEnum.HasValue ? GatewayTypeEnumValueConverter.ToJsonValue(gatewayTypeEnum.Value).ToString() : "null");
        }
    }
}
