// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// MerchantOrderRefundResponse
    /// </summary>
    public partial class MerchantOrderRefundResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MerchantOrderRefundResponse" /> class.
        /// </summary>
        /// <param name="message">message</param>
        /// <param name="orderUuid">orderUuid</param>
        /// <param name="status">status</param>
        /// <param name="statusDisplay">statusDisplay</param>
        /// <param name="refundReason">refundReason</param>
        [JsonConstructor]
        public MerchantOrderRefundResponse(string message, Guid orderUuid, OrderStatusEnum status, string statusDisplay, string refundReason)
        {
            Message = message;
            OrderUuid = orderUuid;
            Status = status;
            StatusDisplay = statusDisplay;
            RefundReason = refundReason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public OrderStatusEnum Status { get; set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets OrderUuid
        /// </summary>
        [JsonPropertyName("order_uuid")]
        public Guid OrderUuid { get; set; }

        /// <summary>
        /// Gets or Sets StatusDisplay
        /// </summary>
        [JsonPropertyName("status_display")]
        public string StatusDisplay { get; set; }

        /// <summary>
        /// Gets or Sets RefundReason
        /// </summary>
        [JsonPropertyName("refund_reason")]
        public string RefundReason { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MerchantOrderRefundResponse {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  OrderUuid: ").Append(OrderUuid).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusDisplay: ").Append(StatusDisplay).Append("\n");
            sb.Append("  RefundReason: ").Append(RefundReason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="MerchantOrderRefundResponse" />
    /// </summary>
    public class MerchantOrderRefundResponseJsonConverter : JsonConverter<MerchantOrderRefundResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="MerchantOrderRefundResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override MerchantOrderRefundResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> message = default;
            Option<Guid?> orderUuid = default;
            Option<OrderStatusEnum?> status = default;
            Option<string?> statusDisplay = default;
            Option<string?> refundReason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "order_uuid":
                            orderUuid = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string? statusRawValue = utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<OrderStatusEnum?>(OrderStatusEnumValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "status_display":
                            statusDisplay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "refund_reason":
                            refundReason = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!message.IsSet)
                throw new ArgumentException("Property is required for class MerchantOrderRefundResponse.", nameof(message));

            if (!orderUuid.IsSet)
                throw new ArgumentException("Property is required for class MerchantOrderRefundResponse.", nameof(orderUuid));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class MerchantOrderRefundResponse.", nameof(status));

            if (!statusDisplay.IsSet)
                throw new ArgumentException("Property is required for class MerchantOrderRefundResponse.", nameof(statusDisplay));

            if (!refundReason.IsSet)
                throw new ArgumentException("Property is required for class MerchantOrderRefundResponse.", nameof(refundReason));

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class MerchantOrderRefundResponse.");

            if (orderUuid.IsSet && orderUuid.Value == null)
                throw new ArgumentNullException(nameof(orderUuid), "Property is not nullable for class MerchantOrderRefundResponse.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class MerchantOrderRefundResponse.");

            if (statusDisplay.IsSet && statusDisplay.Value == null)
                throw new ArgumentNullException(nameof(statusDisplay), "Property is not nullable for class MerchantOrderRefundResponse.");

            if (refundReason.IsSet && refundReason.Value == null)
                throw new ArgumentNullException(nameof(refundReason), "Property is not nullable for class MerchantOrderRefundResponse.");

            return new MerchantOrderRefundResponse(message.Value!, orderUuid.Value!.Value!, status.Value!.Value!, statusDisplay.Value!, refundReason.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="MerchantOrderRefundResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantOrderRefundResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, MerchantOrderRefundResponse merchantOrderRefundResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, merchantOrderRefundResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="MerchantOrderRefundResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="merchantOrderRefundResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, MerchantOrderRefundResponse merchantOrderRefundResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (merchantOrderRefundResponse.Message == null)
                throw new ArgumentNullException(nameof(merchantOrderRefundResponse.Message), "Property is required for class MerchantOrderRefundResponse.");

            if (merchantOrderRefundResponse.StatusDisplay == null)
                throw new ArgumentNullException(nameof(merchantOrderRefundResponse.StatusDisplay), "Property is required for class MerchantOrderRefundResponse.");

            if (merchantOrderRefundResponse.RefundReason == null)
                throw new ArgumentNullException(nameof(merchantOrderRefundResponse.RefundReason), "Property is required for class MerchantOrderRefundResponse.");

            writer.WriteString("message", merchantOrderRefundResponse.Message);

            writer.WriteString("order_uuid", merchantOrderRefundResponse.OrderUuid);

            var statusRawValue = OrderStatusEnumValueConverter.ToJsonValue(merchantOrderRefundResponse.Status);
            writer.WriteNumber("status", statusRawValue);

            writer.WriteString("status_display", merchantOrderRefundResponse.StatusDisplay);

            writer.WriteString("refund_reason", merchantOrderRefundResponse.RefundReason);
        }
    }
}
