// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// Defines NullEnum
    /// </summary>
    public enum NullEnum
    {
    }

    /// <summary>
    /// Converts <see cref="NullEnum"/> to and from the JSON value
    /// </summary>
    public static class NullEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="NullEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullEnum FromString(string value)
        {
            throw new NotImplementedException($"Could not convert value to type NullEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="NullEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static NullEnum? FromStringOrDefault(string value)
        {
            return null;
        }

        /// <summary>
        /// Converts the <see cref="NullEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static  ToJsonValue(NullEnum value)
        {
            throw new NotImplementedException($"Value could not be handled: '{value}'");
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class NullEnumJsonConverter : JsonConverter<NullEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullEnum? result = rawValue == null
                ? null
                : NullEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NullEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullEnum nullEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(NullEnumValueConverter.ToJsonValue(nullEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NullEnum"/>
    /// </summary>
    public class NullEnumNullableJsonConverter : JsonConverter<NullEnum?>
    {
        /// <summary>
        /// Returns a NullEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override NullEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            NullEnum? result = rawValue == null
                ? null
                : NullEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the NullEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="nullEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, NullEnum? nullEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(nullEnum.HasValue ? NullEnumValueConverter.ToJsonValue(nullEnum.Value).ToString() : "null");
        }
    }
}
