// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// Option
    /// </summary>
    public partial class Option : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Option" /> class.
        /// </summary>
        /// <param name="typeName">نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * &#x60;color&#x60; - رنگ * &#x60;size&#x60; - اندازه * &#x60;warranty&#x60; - گارانتی * &#x60;weight&#x60; - وزن * &#x60;other&#x60; - سایر</param>
        /// <param name="name">نام ویژگی (مثلاً &#39;قرمز&#39; برای رنگ قرمز، &#39;XL&#39; برای سایز)</param>
        /// <param name="value">مقدار ویژگی (مثلاً &#39;#FF0000&#39; برای کد رنگ یا مقدار دیگر)</param>
        /// <param name="isColor">اگر نوع ویژگی رنگ است درست است، وگرنه غلط (default to false)</param>
        [JsonConstructor]
        public Option(TypeNameEnum typeName, string name, string value, Option<bool?> isColor = default)
        {
            TypeName = typeName;
            Name = name;
            Value = value;
            IsColorOption = isColor;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * &#x60;color&#x60; - رنگ * &#x60;size&#x60; - اندازه * &#x60;warranty&#x60; - گارانتی * &#x60;weight&#x60; - وزن * &#x60;other&#x60; - سایر
        /// </summary>
        /// <value>نوع ویژگی محصول: رنگ، سایز، گارانتی، وزن یا سایر  * &#x60;color&#x60; - رنگ * &#x60;size&#x60; - اندازه * &#x60;warranty&#x60; - گارانتی * &#x60;weight&#x60; - وزن * &#x60;other&#x60; - سایر</value>
        [JsonPropertyName("type_name")]
        public TypeNameEnum TypeName { get; set; }

        /// <summary>
        /// نام ویژگی (مثلاً &#39;قرمز&#39; برای رنگ قرمز، &#39;XL&#39; برای سایز)
        /// </summary>
        /// <value>نام ویژگی (مثلاً &#39;قرمز&#39; برای رنگ قرمز، &#39;XL&#39; برای سایز)</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// مقدار ویژگی (مثلاً &#39;#FF0000&#39; برای کد رنگ یا مقدار دیگر)
        /// </summary>
        /// <value>مقدار ویژگی (مثلاً &#39;#FF0000&#39; برای کد رنگ یا مقدار دیگر)</value>
        [JsonPropertyName("value")]
        public string Value { get; set; }

        /// <summary>
        /// Used to track the state of IsColor
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsColorOption { get; private set; }

        /// <summary>
        /// اگر نوع ویژگی رنگ است درست است، وگرنه غلط
        /// </summary>
        /// <value>اگر نوع ویژگی رنگ است درست است، وگرنه غلط</value>
        [JsonPropertyName("is_color")]
        public bool? IsColor { get { return this.IsColorOption; } set { this.IsColorOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Option {\n");
            sb.Append("  TypeName: ").Append(TypeName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  IsColor: ").Append(IsColor).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Option" />
    /// </summary>
    public class OptionJsonConverter : JsonConverter<Option>
    {
        /// <summary>
        /// Deserializes json to <see cref="Option" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Option Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<TypeNameEnum?> typeName = default;
            Option<string?> name = default;
            Option<string?> value = default;
            Option<bool?> isColor = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type_name":
                            string? typeNameRawValue = utf8JsonReader.GetString();
                            if (typeNameRawValue != null)
                                typeName = new Option<TypeNameEnum?>(TypeNameEnumValueConverter.FromStringOrDefault(typeNameRawValue));
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "value":
                            value = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "is_color":
                            isColor = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!typeName.IsSet)
                throw new ArgumentException("Property is required for class Option.", nameof(typeName));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class Option.", nameof(name));

            if (!value.IsSet)
                throw new ArgumentException("Property is required for class Option.", nameof(value));

            if (typeName.IsSet && typeName.Value == null)
                throw new ArgumentNullException(nameof(typeName), "Property is not nullable for class Option.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class Option.");

            if (value.IsSet && value.Value == null)
                throw new ArgumentNullException(nameof(value), "Property is not nullable for class Option.");

            if (isColor.IsSet && isColor.Value == null)
                throw new ArgumentNullException(nameof(isColor), "Property is not nullable for class Option.");

            return new Option(typeName.Value!.Value!, name.Value!, value.Value!, isColor);
        }

        /// <summary>
        /// Serializes a <see cref="Option" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="option"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Option option, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, option, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Option" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="option"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Option option, JsonSerializerOptions jsonSerializerOptions)
        {
            if (option.Name == null)
                throw new ArgumentNullException(nameof(option.Name), "Property is required for class Option.");

            if (option.Value == null)
                throw new ArgumentNullException(nameof(option.Value), "Property is required for class Option.");

            var typeNameRawValue = TypeNameEnumValueConverter.ToJsonValue(option.TypeName);
            writer.WriteString("type_name", typeNameRawValue);

            writer.WriteString("name", option.Name);

            writer.WriteString("value", option.Value);

            if (option.IsColorOption.IsSet)
                writer.WriteBoolean("is_color", option.IsColorOption.Value!.Value);
        }
    }
}
