// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// OrderCreateResponse
    /// </summary>
    public partial class OrderCreateResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreateResponse" /> class.
        /// </summary>
        /// <param name="orderStartUrl">orderStartUrl</param>
        /// <param name="orderUuid">orderUuid</param>
        [JsonConstructor]
        public OrderCreateResponse(string orderStartUrl, Guid orderUuid)
        {
            OrderStartUrl = orderStartUrl;
            OrderUuid = orderUuid;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets OrderStartUrl
        /// </summary>
        [JsonPropertyName("order_start_url")]
        public string OrderStartUrl { get; set; }

        /// <summary>
        /// Gets or Sets OrderUuid
        /// </summary>
        [JsonPropertyName("order_uuid")]
        public Guid OrderUuid { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreateResponse {\n");
            sb.Append("  OrderStartUrl: ").Append(OrderStartUrl).Append("\n");
            sb.Append("  OrderUuid: ").Append(OrderUuid).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderCreateResponse" />
    /// </summary>
    public class OrderCreateResponseJsonConverter : JsonConverter<OrderCreateResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrderCreateResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrderCreateResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> orderStartUrl = default;
            Option<Guid?> orderUuid = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "order_start_url":
                            orderStartUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "order_uuid":
                            orderUuid = new Option<Guid?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (Guid?)null : utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!orderStartUrl.IsSet)
                throw new ArgumentException("Property is required for class OrderCreateResponse.", nameof(orderStartUrl));

            if (!orderUuid.IsSet)
                throw new ArgumentException("Property is required for class OrderCreateResponse.", nameof(orderUuid));

            if (orderStartUrl.IsSet && orderStartUrl.Value == null)
                throw new ArgumentNullException(nameof(orderStartUrl), "Property is not nullable for class OrderCreateResponse.");

            if (orderUuid.IsSet && orderUuid.Value == null)
                throw new ArgumentNullException(nameof(orderUuid), "Property is not nullable for class OrderCreateResponse.");

            return new OrderCreateResponse(orderStartUrl.Value!, orderUuid.Value!.Value!);
        }

        /// <summary>
        /// Serializes a <see cref="OrderCreateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderCreateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrderCreateResponse orderCreateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orderCreateResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrderCreateResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderCreateResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrderCreateResponse orderCreateResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orderCreateResponse.OrderStartUrl == null)
                throw new ArgumentNullException(nameof(orderCreateResponse.OrderStartUrl), "Property is required for class OrderCreateResponse.");

            writer.WriteString("order_start_url", orderCreateResponse.OrderStartUrl);

            writer.WriteString("order_uuid", orderCreateResponse.OrderUuid);
        }
    }
}
