// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// * &#x60;1&#x60; - اولیه * &#x60;2&#x60; - شروع شده * &#x60;3&#x60; - در انتظار * &#x60;4&#x60; - در انتظار درگاه * &#x60;5&#x60; - منقضی شده * &#x60;6&#x60; - لغو شده * &#x60;7&#x60; - پرداخت‌شده توسط کاربر * &#x60;8&#x60; - پرداخت موفیت آمیز نبود * &#x60;9&#x60; - تأیید شده توسط فروشگاه * &#x60;10&#x60; - تأیید توسط فروشگاه ناموفق بود * &#x60;11&#x60; - ناموفق از سوی فروشگاه * &#x60;12&#x60; - لغوشده توسط فروشگاه * &#x60;13&#x60; - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * &#x60;14&#x60; - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * &#x60;15&#x60; - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * &#x60;16&#x60; - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * &#x60;17&#x60; - بازپرداخت تکمیل شد * &#x60;18&#x60; - زمان انقضا گذشته است * &#x60;19&#x60; - تحویل شده * &#x60;20&#x60; - جمع اوری شده و در حال ارسال
    /// </summary>
    /// <value>* &#x60;1&#x60; - اولیه * &#x60;2&#x60; - شروع شده * &#x60;3&#x60; - در انتظار * &#x60;4&#x60; - در انتظار درگاه * &#x60;5&#x60; - منقضی شده * &#x60;6&#x60; - لغو شده * &#x60;7&#x60; - پرداخت‌شده توسط کاربر * &#x60;8&#x60; - پرداخت موفیت آمیز نبود * &#x60;9&#x60; - تأیید شده توسط فروشگاه * &#x60;10&#x60; - تأیید توسط فروشگاه ناموفق بود * &#x60;11&#x60; - ناموفق از سوی فروشگاه * &#x60;12&#x60; - لغوشده توسط فروشگاه * &#x60;13&#x60; - درخواست بازگشت وجه به مشتری به دلیل درخواست مشتری * &#x60;14&#x60; - درخواست بازگشت وجه به فروشگاه پس از عدم تأیید توسط فروشگاه * &#x60;15&#x60; - درخواست بازگشت وجه به مشتری پس از ناموفق بودن توسط فروشگاه * &#x60;16&#x60; - بازپرداخت به فروشگاه پس از لغو توسط فروشگاه * &#x60;17&#x60; - بازپرداخت تکمیل شد * &#x60;18&#x60; - زمان انقضا گذشته است * &#x60;19&#x60; - تحویل شده * &#x60;20&#x60; - جمع اوری شده و در حال ارسال</value>
    public enum OrderStatusEnum
    {
        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        NUMBER_6 = 6,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        NUMBER_7 = 7,

        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        NUMBER_8 = 8,

        /// <summary>
        /// Enum NUMBER_9 for value: 9
        /// </summary>
        NUMBER_9 = 9,

        /// <summary>
        /// Enum NUMBER_10 for value: 10
        /// </summary>
        NUMBER_10 = 10,

        /// <summary>
        /// Enum NUMBER_11 for value: 11
        /// </summary>
        NUMBER_11 = 11,

        /// <summary>
        /// Enum NUMBER_12 for value: 12
        /// </summary>
        NUMBER_12 = 12,

        /// <summary>
        /// Enum NUMBER_13 for value: 13
        /// </summary>
        NUMBER_13 = 13,

        /// <summary>
        /// Enum NUMBER_14 for value: 14
        /// </summary>
        NUMBER_14 = 14,

        /// <summary>
        /// Enum NUMBER_15 for value: 15
        /// </summary>
        NUMBER_15 = 15,

        /// <summary>
        /// Enum NUMBER_16 for value: 16
        /// </summary>
        NUMBER_16 = 16,

        /// <summary>
        /// Enum NUMBER_17 for value: 17
        /// </summary>
        NUMBER_17 = 17,

        /// <summary>
        /// Enum NUMBER_18 for value: 18
        /// </summary>
        NUMBER_18 = 18,

        /// <summary>
        /// Enum NUMBER_19 for value: 19
        /// </summary>
        NUMBER_19 = 19,

        /// <summary>
        /// Enum NUMBER_20 for value: 20
        /// </summary>
        NUMBER_20 = 20
    }

    /// <summary>
    /// Converts <see cref="OrderStatusEnum"/> to and from the JSON value
    /// </summary>
    public static class OrderStatusEnumValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="OrderStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OrderStatusEnum FromString(string value)
        {
            if (value.Equals((1).ToString()))
                return OrderStatusEnum.NUMBER_1;

            if (value.Equals((2).ToString()))
                return OrderStatusEnum.NUMBER_2;

            if (value.Equals((3).ToString()))
                return OrderStatusEnum.NUMBER_3;

            if (value.Equals((4).ToString()))
                return OrderStatusEnum.NUMBER_4;

            if (value.Equals((5).ToString()))
                return OrderStatusEnum.NUMBER_5;

            if (value.Equals((6).ToString()))
                return OrderStatusEnum.NUMBER_6;

            if (value.Equals((7).ToString()))
                return OrderStatusEnum.NUMBER_7;

            if (value.Equals((8).ToString()))
                return OrderStatusEnum.NUMBER_8;

            if (value.Equals((9).ToString()))
                return OrderStatusEnum.NUMBER_9;

            if (value.Equals((10).ToString()))
                return OrderStatusEnum.NUMBER_10;

            if (value.Equals((11).ToString()))
                return OrderStatusEnum.NUMBER_11;

            if (value.Equals((12).ToString()))
                return OrderStatusEnum.NUMBER_12;

            if (value.Equals((13).ToString()))
                return OrderStatusEnum.NUMBER_13;

            if (value.Equals((14).ToString()))
                return OrderStatusEnum.NUMBER_14;

            if (value.Equals((15).ToString()))
                return OrderStatusEnum.NUMBER_15;

            if (value.Equals((16).ToString()))
                return OrderStatusEnum.NUMBER_16;

            if (value.Equals((17).ToString()))
                return OrderStatusEnum.NUMBER_17;

            if (value.Equals((18).ToString()))
                return OrderStatusEnum.NUMBER_18;

            if (value.Equals((19).ToString()))
                return OrderStatusEnum.NUMBER_19;

            if (value.Equals((20).ToString()))
                return OrderStatusEnum.NUMBER_20;

            throw new NotImplementedException($"Could not convert value to type OrderStatusEnum: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="OrderStatusEnum"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static OrderStatusEnum? FromStringOrDefault(string value)
        {
            if (value.Equals((1).ToString()))
                return OrderStatusEnum.NUMBER_1;

            if (value.Equals((2).ToString()))
                return OrderStatusEnum.NUMBER_2;

            if (value.Equals((3).ToString()))
                return OrderStatusEnum.NUMBER_3;

            if (value.Equals((4).ToString()))
                return OrderStatusEnum.NUMBER_4;

            if (value.Equals((5).ToString()))
                return OrderStatusEnum.NUMBER_5;

            if (value.Equals((6).ToString()))
                return OrderStatusEnum.NUMBER_6;

            if (value.Equals((7).ToString()))
                return OrderStatusEnum.NUMBER_7;

            if (value.Equals((8).ToString()))
                return OrderStatusEnum.NUMBER_8;

            if (value.Equals((9).ToString()))
                return OrderStatusEnum.NUMBER_9;

            if (value.Equals((10).ToString()))
                return OrderStatusEnum.NUMBER_10;

            if (value.Equals((11).ToString()))
                return OrderStatusEnum.NUMBER_11;

            if (value.Equals((12).ToString()))
                return OrderStatusEnum.NUMBER_12;

            if (value.Equals((13).ToString()))
                return OrderStatusEnum.NUMBER_13;

            if (value.Equals((14).ToString()))
                return OrderStatusEnum.NUMBER_14;

            if (value.Equals((15).ToString()))
                return OrderStatusEnum.NUMBER_15;

            if (value.Equals((16).ToString()))
                return OrderStatusEnum.NUMBER_16;

            if (value.Equals((17).ToString()))
                return OrderStatusEnum.NUMBER_17;

            if (value.Equals((18).ToString()))
                return OrderStatusEnum.NUMBER_18;

            if (value.Equals((19).ToString()))
                return OrderStatusEnum.NUMBER_19;

            if (value.Equals((20).ToString()))
                return OrderStatusEnum.NUMBER_20;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="OrderStatusEnum"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(OrderStatusEnum value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderStatusEnum"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class OrderStatusEnumJsonConverter : JsonConverter<OrderStatusEnum>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OrderStatusEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OrderStatusEnum? result = rawValue == null
                ? null
                : OrderStatusEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OrderStatusEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderStatusEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OrderStatusEnum orderStatusEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(OrderStatusEnumValueConverter.ToJsonValue(orderStatusEnum).ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderStatusEnum"/>
    /// </summary>
    public class OrderStatusEnumNullableJsonConverter : JsonConverter<OrderStatusEnum?>
    {
        /// <summary>
        /// Returns a OrderStatusEnum from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override OrderStatusEnum? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? rawValue = reader.GetString();

            OrderStatusEnum? result = rawValue == null
                ? null
                : OrderStatusEnumValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the OrderStatusEnum to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderStatusEnum"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, OrderStatusEnum? orderStatusEnum, JsonSerializerOptions options)
        {
            writer.WriteStringValue(orderStatusEnum.HasValue ? OrderStatusEnumValueConverter.ToJsonValue(orderStatusEnum.Value).ToString() : "null");
        }
    }
}
