// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// OrderCreate
    /// </summary>
    public partial class OrderCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderCreate" /> class.
        /// </summary>
        /// <param name="merchantOrderId">شناسه منحصر به فرد این سفارش در سیستم فروشنده</param>
        /// <param name="merchantUniqueId">شناسه منحصر به فرد برای تأیید اصالت سفارش</param>
        /// <param name="callbackUrl">آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت</param>
        /// <param name="items">items</param>
        /// <param name="referenceCode">کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)</param>
        /// <param name="mainAmount">مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)</param>
        /// <param name="finalAmount">مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)</param>
        /// <param name="totalPaidAmount">مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)</param>
        /// <param name="discountAmount">مبلغ کل تخفیف برای تمام سفارش (به تومان)</param>
        /// <param name="taxAmount">مبلغ کل مالیات برای تمام سفارش (به تومان)</param>
        /// <param name="shippingAmount">هزینه ارسال برای سفارش (به تومان)</param>
        /// <param name="loyaltyAmount">مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)</param>
        /// <param name="destinationAddress">destinationAddress</param>
        /// <param name="merchant">مقدار توسط سیستم جایگذاری می شود</param>
        /// <param name="sourceAddress">مقدار توسط سیستم جایگذاری می شود</param>
        /// <param name="user">user</param>
        /// <param name="reservationExpiredAt">مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش</param>
        /// <param name="preparationTime">Preparation time for the order (in days) (default to 2)</param>
        /// <param name="weight">Total Weight of the order (in grams)</param>
        [JsonConstructor]
        public OrderCreate(string merchantOrderId, string merchantUniqueId, string callbackUrl, List<OrderItemCreate> items, string referenceCode, Option<int?> mainAmount = default, Option<int?> finalAmount = default, Option<int?> totalPaidAmount = default, Option<int?> discountAmount = default, Option<int?> taxAmount = default, Option<int?> shippingAmount = default, Option<int?> loyaltyAmount = default, Object? destinationAddress = default, Option<int?> merchant = default, Option<Object?> sourceAddress = default, int? user = default, Option<int?> reservationExpiredAt = default, Option<int?> preparationTime = default, Option<double?> weight = default)
        {
            MerchantOrderId = merchantOrderId;
            MerchantUniqueId = merchantUniqueId;
            CallbackUrl = callbackUrl;
            Items = items;
            ReferenceCode = referenceCode;
            MainAmountOption = mainAmount;
            FinalAmountOption = finalAmount;
            TotalPaidAmountOption = totalPaidAmount;
            DiscountAmountOption = discountAmount;
            TaxAmountOption = taxAmount;
            ShippingAmountOption = shippingAmount;
            LoyaltyAmountOption = loyaltyAmount;
            DestinationAddress = destinationAddress;
            MerchantOption = merchant;
            SourceAddressOption = sourceAddress;
            User = user;
            ReservationExpiredAtOption = reservationExpiredAt;
            PreparationTimeOption = preparationTime;
            WeightOption = weight;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// شناسه منحصر به فرد این سفارش در سیستم فروشنده
        /// </summary>
        /// <value>شناسه منحصر به فرد این سفارش در سیستم فروشنده</value>
        [JsonPropertyName("merchant_order_id")]
        public string MerchantOrderId { get; set; }

        /// <summary>
        /// شناسه منحصر به فرد برای تأیید اصالت سفارش
        /// </summary>
        /// <value>شناسه منحصر به فرد برای تأیید اصالت سفارش</value>
        [JsonPropertyName("merchant_unique_id")]
        public string MerchantUniqueId { get; set; }

        /// <summary>
        /// آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت
        /// </summary>
        /// <value>آدرس وب‌هوک برای دریافت اطلاع رسانی وضعیت پرداخت</value>
        [JsonPropertyName("callback_url")]
        public string CallbackUrl { get; set; }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [JsonPropertyName("items")]
        public List<OrderItemCreate> Items { get; set; }

        /// <summary>
        /// کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)
        /// </summary>
        /// <value>کد مرجع یکتا برای پیگیری سفارش مشتری (قالب: BD-XXXXXXXX)</value>
        [JsonPropertyName("reference_code")]
        public string ReferenceCode { get; }

        /// <summary>
        /// Used to track the state of MainAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MainAmountOption { get; private set; }

        /// <summary>
        /// مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)
        /// </summary>
        /// <value>مجموع قیمت‌های اولیه تمام کالاها بدون تخفیف (به تومان)</value>
        [JsonPropertyName("main_amount")]
        public int? MainAmount { get { return this.MainAmountOption; } set { this.MainAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of FinalAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> FinalAmountOption { get; private set; }

        /// <summary>
        /// مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)
        /// </summary>
        /// <value>مبلغ نهایی: مبلغ_اصلی - مبلغ_تخفیف + مبلغ_مالیات (به تومان)</value>
        [JsonPropertyName("final_amount")]
        public int? FinalAmount { get { return this.FinalAmountOption; } set { this.FinalAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TotalPaidAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TotalPaidAmountOption { get; private set; }

        /// <summary>
        /// مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)
        /// </summary>
        /// <value>مبلغ کل پرداخت شده توسط کاربر: مبلغ_نهایی + هزینه_ارسال (به تومان)</value>
        [JsonPropertyName("total_paid_amount")]
        public int? TotalPaidAmount { get { return this.TotalPaidAmountOption; } set { this.TotalPaidAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DiscountAmountOption { get; private set; }

        /// <summary>
        /// مبلغ کل تخفیف برای تمام سفارش (به تومان)
        /// </summary>
        /// <value>مبلغ کل تخفیف برای تمام سفارش (به تومان)</value>
        [JsonPropertyName("discount_amount")]
        public int? DiscountAmount { get { return this.DiscountAmountOption; } set { this.DiscountAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TaxAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TaxAmountOption { get; private set; }

        /// <summary>
        /// مبلغ کل مالیات برای تمام سفارش (به تومان)
        /// </summary>
        /// <value>مبلغ کل مالیات برای تمام سفارش (به تومان)</value>
        [JsonPropertyName("tax_amount")]
        public int? TaxAmount { get { return this.TaxAmountOption; } set { this.TaxAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ShippingAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ShippingAmountOption { get; private set; }

        /// <summary>
        /// هزینه ارسال برای سفارش (به تومان)
        /// </summary>
        /// <value>هزینه ارسال برای سفارش (به تومان)</value>
        [JsonPropertyName("shipping_amount")]
        public int? ShippingAmount { get { return this.ShippingAmountOption; } set { this.ShippingAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of LoyaltyAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> LoyaltyAmountOption { get; private set; }

        /// <summary>
        /// مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)
        /// </summary>
        /// <value>مبلغ تخفیف باشگاه مشتریان/پاداش (به تومان)</value>
        [JsonPropertyName("loyalty_amount")]
        public int? LoyaltyAmount { get { return this.LoyaltyAmountOption; } set { this.LoyaltyAmountOption = new(value); } }

        /// <summary>
        /// Gets or Sets DestinationAddress
        /// </summary>
        [JsonPropertyName("destination_address")]
        public Object? DestinationAddress { get; }

        /// <summary>
        /// Used to track the state of Merchant
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MerchantOption { get; private set; }

        /// <summary>
        /// مقدار توسط سیستم جایگذاری می شود
        /// </summary>
        /// <value>مقدار توسط سیستم جایگذاری می شود</value>
        [JsonPropertyName("merchant")]
        public int? Merchant { get { return this.MerchantOption; } set { this.MerchantOption = new(value); } }

        /// <summary>
        /// Used to track the state of SourceAddress
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> SourceAddressOption { get; private set; }

        /// <summary>
        /// مقدار توسط سیستم جایگذاری می شود
        /// </summary>
        /// <value>مقدار توسط سیستم جایگذاری می شود</value>
        [JsonPropertyName("source_address")]
        public Object? SourceAddress { get { return this.SourceAddressOption; } set { this.SourceAddressOption = new(value); } }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [JsonPropertyName("user")]
        public int? User { get; }

        /// <summary>
        /// Used to track the state of ReservationExpiredAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> ReservationExpiredAtOption { get; private set; }

        /// <summary>
        /// مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش
        /// </summary>
        /// <value>مهلت پرداخت (به عنوان Unix timestamp) قبل از اتمام سفارش</value>
        [JsonPropertyName("reservation_expired_at")]
        public int? ReservationExpiredAt { get { return this.ReservationExpiredAtOption; } set { this.ReservationExpiredAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of PreparationTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PreparationTimeOption { get; private set; }

        /// <summary>
        /// Preparation time for the order (in days)
        /// </summary>
        /// <value>Preparation time for the order (in days)</value>
        [JsonPropertyName("preparation_time")]
        public int? PreparationTime { get { return this.PreparationTimeOption; } set { this.PreparationTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Weight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> WeightOption { get; private set; }

        /// <summary>
        /// Total Weight of the order (in grams)
        /// </summary>
        /// <value>Total Weight of the order (in grams)</value>
        [JsonPropertyName("weight")]
        public double? Weight { get { return this.WeightOption; } set { this.WeightOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderCreate {\n");
            sb.Append("  MerchantOrderId: ").Append(MerchantOrderId).Append("\n");
            sb.Append("  MerchantUniqueId: ").Append(MerchantUniqueId).Append("\n");
            sb.Append("  CallbackUrl: ").Append(CallbackUrl).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  ReferenceCode: ").Append(ReferenceCode).Append("\n");
            sb.Append("  MainAmount: ").Append(MainAmount).Append("\n");
            sb.Append("  FinalAmount: ").Append(FinalAmount).Append("\n");
            sb.Append("  TotalPaidAmount: ").Append(TotalPaidAmount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  TaxAmount: ").Append(TaxAmount).Append("\n");
            sb.Append("  ShippingAmount: ").Append(ShippingAmount).Append("\n");
            sb.Append("  LoyaltyAmount: ").Append(LoyaltyAmount).Append("\n");
            sb.Append("  DestinationAddress: ").Append(DestinationAddress).Append("\n");
            sb.Append("  Merchant: ").Append(Merchant).Append("\n");
            sb.Append("  SourceAddress: ").Append(SourceAddress).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("  ReservationExpiredAt: ").Append(ReservationExpiredAt).Append("\n");
            sb.Append("  PreparationTime: ").Append(PreparationTime).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // MerchantOrderId (string) maxLength
            if (this.MerchantOrderId != null && this.MerchantOrderId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for MerchantOrderId, length must be less than 64.", new [] { "MerchantOrderId" });
            }

            // MerchantUniqueId (string) maxLength
            if (this.MerchantUniqueId != null && this.MerchantUniqueId.Length > 64)
            {
                yield return new ValidationResult("Invalid value for MerchantUniqueId, length must be less than 64.", new [] { "MerchantUniqueId" });
            }

            // CallbackUrl (string) maxLength
            if (this.CallbackUrl != null && this.CallbackUrl.Length > 256)
            {
                yield return new ValidationResult("Invalid value for CallbackUrl, length must be less than 256.", new [] { "CallbackUrl" });
            }

            // MainAmount (int) maximum
            if (this.MainAmountOption.IsSet && this.MainAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for MainAmount, must be a value less than or equal to 2147483647.", new [] { "MainAmount" });
            }

            // MainAmount (int) minimum
            if (this.MainAmountOption.IsSet && this.MainAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for MainAmount, must be a value greater than or equal to 0.", new [] { "MainAmount" });
            }

            // FinalAmount (int) maximum
            if (this.FinalAmountOption.IsSet && this.FinalAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for FinalAmount, must be a value less than or equal to 2147483647.", new [] { "FinalAmount" });
            }

            // FinalAmount (int) minimum
            if (this.FinalAmountOption.IsSet && this.FinalAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for FinalAmount, must be a value greater than or equal to 0.", new [] { "FinalAmount" });
            }

            // TotalPaidAmount (int) maximum
            if (this.TotalPaidAmountOption.IsSet && this.TotalPaidAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for TotalPaidAmount, must be a value less than or equal to 2147483647.", new [] { "TotalPaidAmount" });
            }

            // TotalPaidAmount (int) minimum
            if (this.TotalPaidAmountOption.IsSet && this.TotalPaidAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for TotalPaidAmount, must be a value greater than or equal to 0.", new [] { "TotalPaidAmount" });
            }

            // DiscountAmount (int) maximum
            if (this.DiscountAmountOption.IsSet && this.DiscountAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for DiscountAmount, must be a value less than or equal to 2147483647.", new [] { "DiscountAmount" });
            }

            // DiscountAmount (int) minimum
            if (this.DiscountAmountOption.IsSet && this.DiscountAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for DiscountAmount, must be a value greater than or equal to 0.", new [] { "DiscountAmount" });
            }

            // TaxAmount (int) maximum
            if (this.TaxAmountOption.IsSet && this.TaxAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for TaxAmount, must be a value less than or equal to 2147483647.", new [] { "TaxAmount" });
            }

            // TaxAmount (int) minimum
            if (this.TaxAmountOption.IsSet && this.TaxAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for TaxAmount, must be a value greater than or equal to 0.", new [] { "TaxAmount" });
            }

            // ShippingAmount (int) maximum
            if (this.ShippingAmountOption.IsSet && this.ShippingAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for ShippingAmount, must be a value less than or equal to 2147483647.", new [] { "ShippingAmount" });
            }

            // ShippingAmount (int) minimum
            if (this.ShippingAmountOption.IsSet && this.ShippingAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for ShippingAmount, must be a value greater than or equal to 0.", new [] { "ShippingAmount" });
            }

            // LoyaltyAmount (int) maximum
            if (this.LoyaltyAmountOption.IsSet && this.LoyaltyAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for LoyaltyAmount, must be a value less than or equal to 2147483647.", new [] { "LoyaltyAmount" });
            }

            // LoyaltyAmount (int) minimum
            if (this.LoyaltyAmountOption.IsSet && this.LoyaltyAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for LoyaltyAmount, must be a value greater than or equal to 0.", new [] { "LoyaltyAmount" });
            }

            // ReservationExpiredAt (int) maximum
            if (this.ReservationExpiredAtOption.IsSet && this.ReservationExpiredAtOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for ReservationExpiredAt, must be a value less than or equal to 2147483647.", new [] { "ReservationExpiredAt" });
            }

            // ReservationExpiredAt (int) minimum
            if (this.ReservationExpiredAtOption.IsSet && this.ReservationExpiredAtOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for ReservationExpiredAt, must be a value greater than or equal to 0.", new [] { "ReservationExpiredAt" });
            }

            // PreparationTime (int) minimum
            if (this.PreparationTimeOption.IsSet && this.PreparationTimeOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PreparationTime, must be a value greater than or equal to 0.", new [] { "PreparationTime" });
            }

            // Weight (double) minimum
            if (this.WeightOption.IsSet && this.WeightOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for Weight, must be a value greater than or equal to 0.", new [] { "Weight" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderCreate" />
    /// </summary>
    public class OrderCreateJsonConverter : JsonConverter<OrderCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrderCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrderCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> merchantOrderId = default;
            Option<string?> merchantUniqueId = default;
            Option<string?> callbackUrl = default;
            Option<List<OrderItemCreate>?> items = default;
            Option<string?> referenceCode = default;
            Option<int?> mainAmount = default;
            Option<int?> finalAmount = default;
            Option<int?> totalPaidAmount = default;
            Option<int?> discountAmount = default;
            Option<int?> taxAmount = default;
            Option<int?> shippingAmount = default;
            Option<int?> loyaltyAmount = default;
            Option<Object?> destinationAddress = default;
            Option<int?> merchant = default;
            Option<Object?> sourceAddress = default;
            Option<int?> user = default;
            Option<int?> reservationExpiredAt = default;
            Option<int?> preparationTime = default;
            Option<double?> weight = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "merchant_order_id":
                            merchantOrderId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "merchant_unique_id":
                            merchantUniqueId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "callback_url":
                            callbackUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "items":
                            items = new Option<List<OrderItemCreate>?>(JsonSerializer.Deserialize<List<OrderItemCreate>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "reference_code":
                            referenceCode = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "main_amount":
                            mainAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "final_amount":
                            finalAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "total_paid_amount":
                            totalPaidAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "discount_amount":
                            discountAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tax_amount":
                            taxAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "shipping_amount":
                            shippingAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "loyalty_amount":
                            loyaltyAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "destination_address":
                            destinationAddress = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "merchant":
                            merchant = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "source_address":
                            sourceAddress = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "user":
                            user = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "reservation_expired_at":
                            reservationExpiredAt = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "preparation_time":
                            preparationTime = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "weight":
                            weight = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!merchantOrderId.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(merchantOrderId));

            if (!merchantUniqueId.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(merchantUniqueId));

            if (!callbackUrl.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(callbackUrl));

            if (!items.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(items));

            if (!referenceCode.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(referenceCode));

            if (!destinationAddress.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(destinationAddress));

            if (!user.IsSet)
                throw new ArgumentException("Property is required for class OrderCreate.", nameof(user));

            if (merchantOrderId.IsSet && merchantOrderId.Value == null)
                throw new ArgumentNullException(nameof(merchantOrderId), "Property is not nullable for class OrderCreate.");

            if (merchantUniqueId.IsSet && merchantUniqueId.Value == null)
                throw new ArgumentNullException(nameof(merchantUniqueId), "Property is not nullable for class OrderCreate.");

            if (callbackUrl.IsSet && callbackUrl.Value == null)
                throw new ArgumentNullException(nameof(callbackUrl), "Property is not nullable for class OrderCreate.");

            if (items.IsSet && items.Value == null)
                throw new ArgumentNullException(nameof(items), "Property is not nullable for class OrderCreate.");

            if (referenceCode.IsSet && referenceCode.Value == null)
                throw new ArgumentNullException(nameof(referenceCode), "Property is not nullable for class OrderCreate.");

            if (mainAmount.IsSet && mainAmount.Value == null)
                throw new ArgumentNullException(nameof(mainAmount), "Property is not nullable for class OrderCreate.");

            if (finalAmount.IsSet && finalAmount.Value == null)
                throw new ArgumentNullException(nameof(finalAmount), "Property is not nullable for class OrderCreate.");

            if (totalPaidAmount.IsSet && totalPaidAmount.Value == null)
                throw new ArgumentNullException(nameof(totalPaidAmount), "Property is not nullable for class OrderCreate.");

            if (discountAmount.IsSet && discountAmount.Value == null)
                throw new ArgumentNullException(nameof(discountAmount), "Property is not nullable for class OrderCreate.");

            if (taxAmount.IsSet && taxAmount.Value == null)
                throw new ArgumentNullException(nameof(taxAmount), "Property is not nullable for class OrderCreate.");

            if (shippingAmount.IsSet && shippingAmount.Value == null)
                throw new ArgumentNullException(nameof(shippingAmount), "Property is not nullable for class OrderCreate.");

            if (loyaltyAmount.IsSet && loyaltyAmount.Value == null)
                throw new ArgumentNullException(nameof(loyaltyAmount), "Property is not nullable for class OrderCreate.");

            if (merchant.IsSet && merchant.Value == null)
                throw new ArgumentNullException(nameof(merchant), "Property is not nullable for class OrderCreate.");

            if (preparationTime.IsSet && preparationTime.Value == null)
                throw new ArgumentNullException(nameof(preparationTime), "Property is not nullable for class OrderCreate.");

            if (weight.IsSet && weight.Value == null)
                throw new ArgumentNullException(nameof(weight), "Property is not nullable for class OrderCreate.");

            return new OrderCreate(merchantOrderId.Value!, merchantUniqueId.Value!, callbackUrl.Value!, items.Value!, referenceCode.Value!, mainAmount, finalAmount, totalPaidAmount, discountAmount, taxAmount, shippingAmount, loyaltyAmount, destinationAddress.Value!, merchant, sourceAddress, user.Value!, reservationExpiredAt, preparationTime, weight);
        }

        /// <summary>
        /// Serializes a <see cref="OrderCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrderCreate orderCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orderCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrderCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrderCreate orderCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orderCreate.MerchantOrderId == null)
                throw new ArgumentNullException(nameof(orderCreate.MerchantOrderId), "Property is required for class OrderCreate.");

            if (orderCreate.MerchantUniqueId == null)
                throw new ArgumentNullException(nameof(orderCreate.MerchantUniqueId), "Property is required for class OrderCreate.");

            if (orderCreate.CallbackUrl == null)
                throw new ArgumentNullException(nameof(orderCreate.CallbackUrl), "Property is required for class OrderCreate.");

            if (orderCreate.Items == null)
                throw new ArgumentNullException(nameof(orderCreate.Items), "Property is required for class OrderCreate.");

            if (orderCreate.ReferenceCode == null)
                throw new ArgumentNullException(nameof(orderCreate.ReferenceCode), "Property is required for class OrderCreate.");

            writer.WriteString("merchant_order_id", orderCreate.MerchantOrderId);

            writer.WriteString("merchant_unique_id", orderCreate.MerchantUniqueId);

            writer.WriteString("callback_url", orderCreate.CallbackUrl);

            writer.WritePropertyName("items");
            JsonSerializer.Serialize(writer, orderCreate.Items, jsonSerializerOptions);
            writer.WriteString("reference_code", orderCreate.ReferenceCode);

            if (orderCreate.MainAmountOption.IsSet)
                writer.WriteNumber("main_amount", orderCreate.MainAmountOption.Value!.Value);

            if (orderCreate.FinalAmountOption.IsSet)
                writer.WriteNumber("final_amount", orderCreate.FinalAmountOption.Value!.Value);

            if (orderCreate.TotalPaidAmountOption.IsSet)
                writer.WriteNumber("total_paid_amount", orderCreate.TotalPaidAmountOption.Value!.Value);

            if (orderCreate.DiscountAmountOption.IsSet)
                writer.WriteNumber("discount_amount", orderCreate.DiscountAmountOption.Value!.Value);

            if (orderCreate.TaxAmountOption.IsSet)
                writer.WriteNumber("tax_amount", orderCreate.TaxAmountOption.Value!.Value);

            if (orderCreate.ShippingAmountOption.IsSet)
                writer.WriteNumber("shipping_amount", orderCreate.ShippingAmountOption.Value!.Value);

            if (orderCreate.LoyaltyAmountOption.IsSet)
                writer.WriteNumber("loyalty_amount", orderCreate.LoyaltyAmountOption.Value!.Value);

            if (orderCreate.DestinationAddress != null)
            {
                writer.WritePropertyName("destination_address");
                JsonSerializer.Serialize(writer, orderCreate.DestinationAddress, jsonSerializerOptions);
            }
            else
                writer.WriteNull("destination_address");
            if (orderCreate.MerchantOption.IsSet)
                writer.WriteNumber("merchant", orderCreate.MerchantOption.Value!.Value);

            if (orderCreate.SourceAddressOption.IsSet)
                if (orderCreate.SourceAddressOption.Value != null)
                {
                    writer.WritePropertyName("source_address");
                    JsonSerializer.Serialize(writer, orderCreate.SourceAddress, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("source_address");
            if (orderCreate.User != null)
                writer.WriteNumber("user", orderCreate.User.Value);
            else
                writer.WriteNull("user");

            if (orderCreate.ReservationExpiredAtOption.IsSet)
                if (orderCreate.ReservationExpiredAtOption.Value != null)
                    writer.WriteNumber("reservation_expired_at", orderCreate.ReservationExpiredAtOption.Value!.Value);
                else
                    writer.WriteNull("reservation_expired_at");

            if (orderCreate.PreparationTimeOption.IsSet)
                writer.WriteNumber("preparation_time", orderCreate.PreparationTimeOption.Value!.Value);

            if (orderCreate.WeightOption.IsSet)
                writer.WriteNumber("weight", orderCreate.WeightOption.Value!.Value);
        }
    }
}
