// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// OrderItemCreate
    /// </summary>
    public partial class OrderItemCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrderItemCreate" /> class.
        /// </summary>
        /// <param name="name">نام کامل محصول شامل تمام مشخصات</param>
        /// <param name="count">تعداد واحدهای این کالا در سفارش</param>
        /// <param name="options">options</param>
        /// <param name="primaryAmount">قیمت اولیه برای هر واحد بدون تخفیف (به تومان)</param>
        /// <param name="amount">قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)</param>
        /// <param name="discountAmount">مبلغ کل تخفیف برای این کالا (به تومان)</param>
        /// <param name="taxAmount">مبلغ کل مالیات برای این کالا (به تومان)</param>
        /// <param name="imageLink">آدرس تصویر محصول</param>
        /// <param name="preparationTime">Preparation time for the item (in days) (default to 2)</param>
        /// <param name="weight">Weight of the item (in grams)</param>
        [JsonConstructor]
        public OrderItemCreate(string name, int count, List<Option> options, Option<int?> primaryAmount = default, Option<int?> amount = default, Option<int?> discountAmount = default, Option<int?> taxAmount = default, Option<string?> imageLink = default, Option<int?> preparationTime = default, Option<double?> weight = default)
        {
            Name = name;
            Count = count;
            Options = options;
            PrimaryAmountOption = primaryAmount;
            AmountOption = amount;
            DiscountAmountOption = discountAmount;
            TaxAmountOption = taxAmount;
            ImageLinkOption = imageLink;
            PreparationTimeOption = preparationTime;
            WeightOption = weight;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// نام کامل محصول شامل تمام مشخصات
        /// </summary>
        /// <value>نام کامل محصول شامل تمام مشخصات</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// تعداد واحدهای این کالا در سفارش
        /// </summary>
        /// <value>تعداد واحدهای این کالا در سفارش</value>
        [JsonPropertyName("count")]
        public int Count { get; set; }

        /// <summary>
        /// Gets or Sets Options
        /// </summary>
        [JsonPropertyName("options")]
        public List<Option> Options { get; set; }

        /// <summary>
        /// Used to track the state of PrimaryAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PrimaryAmountOption { get; private set; }

        /// <summary>
        /// قیمت اولیه برای هر واحد بدون تخفیف (به تومان)
        /// </summary>
        /// <value>قیمت اولیه برای هر واحد بدون تخفیف (به تومان)</value>
        [JsonPropertyName("primary_amount")]
        public int? PrimaryAmount { get { return this.PrimaryAmountOption; } set { this.PrimaryAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> AmountOption { get; private set; }

        /// <summary>
        /// قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)
        /// </summary>
        /// <value>قیمت نهایی برای تمام واحدها بعد از تخفیف (به تومان)</value>
        [JsonPropertyName("amount")]
        public int? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of DiscountAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> DiscountAmountOption { get; private set; }

        /// <summary>
        /// مبلغ کل تخفیف برای این کالا (به تومان)
        /// </summary>
        /// <value>مبلغ کل تخفیف برای این کالا (به تومان)</value>
        [JsonPropertyName("discount_amount")]
        public int? DiscountAmount { get { return this.DiscountAmountOption; } set { this.DiscountAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of TaxAmount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TaxAmountOption { get; private set; }

        /// <summary>
        /// مبلغ کل مالیات برای این کالا (به تومان)
        /// </summary>
        /// <value>مبلغ کل مالیات برای این کالا (به تومان)</value>
        [JsonPropertyName("tax_amount")]
        public int? TaxAmount { get { return this.TaxAmountOption; } set { this.TaxAmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageLink
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageLinkOption { get; private set; }

        /// <summary>
        /// آدرس تصویر محصول
        /// </summary>
        /// <value>آدرس تصویر محصول</value>
        [JsonPropertyName("image_link")]
        public string? ImageLink { get { return this.ImageLinkOption; } set { this.ImageLinkOption = new(value); } }

        /// <summary>
        /// Used to track the state of PreparationTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PreparationTimeOption { get; private set; }

        /// <summary>
        /// Preparation time for the item (in days)
        /// </summary>
        /// <value>Preparation time for the item (in days)</value>
        [JsonPropertyName("preparation_time")]
        public int? PreparationTime { get { return this.PreparationTimeOption; } set { this.PreparationTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Weight
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> WeightOption { get; private set; }

        /// <summary>
        /// Weight of the item (in grams)
        /// </summary>
        /// <value>Weight of the item (in grams)</value>
        [JsonPropertyName("weight")]
        public double? Weight { get { return this.WeightOption; } set { this.WeightOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrderItemCreate {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Count: ").Append(Count).Append("\n");
            sb.Append("  Options: ").Append(Options).Append("\n");
            sb.Append("  PrimaryAmount: ").Append(PrimaryAmount).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  DiscountAmount: ").Append(DiscountAmount).Append("\n");
            sb.Append("  TaxAmount: ").Append(TaxAmount).Append("\n");
            sb.Append("  ImageLink: ").Append(ImageLink).Append("\n");
            sb.Append("  PreparationTime: ").Append(PreparationTime).Append("\n");
            sb.Append("  Weight: ").Append(Weight).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 128)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 128.", new [] { "Name" });
            }

            // Count (int) maximum
            if (this.Count > (int)32767)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value less than or equal to 32767.", new [] { "Count" });
            }

            // Count (int) minimum
            if (this.Count < (int)0)
            {
                yield return new ValidationResult("Invalid value for Count, must be a value greater than or equal to 0.", new [] { "Count" });
            }

            // PrimaryAmount (int) maximum
            if (this.PrimaryAmountOption.IsSet && this.PrimaryAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for PrimaryAmount, must be a value less than or equal to 2147483647.", new [] { "PrimaryAmount" });
            }

            // PrimaryAmount (int) minimum
            if (this.PrimaryAmountOption.IsSet && this.PrimaryAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PrimaryAmount, must be a value greater than or equal to 0.", new [] { "PrimaryAmount" });
            }

            // Amount (int) maximum
            if (this.AmountOption.IsSet && this.AmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value less than or equal to 2147483647.", new [] { "Amount" });
            }

            // Amount (int) minimum
            if (this.AmountOption.IsSet && this.AmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Amount, must be a value greater than or equal to 0.", new [] { "Amount" });
            }

            // DiscountAmount (int) maximum
            if (this.DiscountAmountOption.IsSet && this.DiscountAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for DiscountAmount, must be a value less than or equal to 2147483647.", new [] { "DiscountAmount" });
            }

            // DiscountAmount (int) minimum
            if (this.DiscountAmountOption.IsSet && this.DiscountAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for DiscountAmount, must be a value greater than or equal to 0.", new [] { "DiscountAmount" });
            }

            // TaxAmount (int) maximum
            if (this.TaxAmountOption.IsSet && this.TaxAmountOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for TaxAmount, must be a value less than or equal to 2147483647.", new [] { "TaxAmount" });
            }

            // TaxAmount (int) minimum
            if (this.TaxAmountOption.IsSet && this.TaxAmountOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for TaxAmount, must be a value greater than or equal to 0.", new [] { "TaxAmount" });
            }

            // ImageLink (string) maxLength
            if (this.ImageLink != null && this.ImageLink.Length > 500)
            {
                yield return new ValidationResult("Invalid value for ImageLink, length must be less than 500.", new [] { "ImageLink" });
            }

            // PreparationTime (int) minimum
            if (this.PreparationTimeOption.IsSet && this.PreparationTimeOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for PreparationTime, must be a value greater than or equal to 0.", new [] { "PreparationTime" });
            }

            // Weight (double) minimum
            if (this.WeightOption.IsSet && this.WeightOption.Value < (double)0)
            {
                yield return new ValidationResult("Invalid value for Weight, must be a value greater than or equal to 0.", new [] { "Weight" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrderItemCreate" />
    /// </summary>
    public class OrderItemCreateJsonConverter : JsonConverter<OrderItemCreate>
    {
        /// <summary>
        /// Deserializes json to <see cref="OrderItemCreate" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrderItemCreate Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<int?> count = default;
            Option<List<Option>?> options = default;
            Option<int?> primaryAmount = default;
            Option<int?> amount = default;
            Option<int?> discountAmount = default;
            Option<int?> taxAmount = default;
            Option<string?> imageLink = default;
            Option<int?> preparationTime = default;
            Option<double?> weight = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "count":
                            count = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "options":
                            options = new Option<List<Option>?>(JsonSerializer.Deserialize<List<Option>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "primary_amount":
                            primaryAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "amount":
                            amount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "discount_amount":
                            discountAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "tax_amount":
                            taxAmount = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "image_link":
                            imageLink = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "preparation_time":
                            preparationTime = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "weight":
                            weight = new Option<double?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (double?)null : utf8JsonReader.GetDouble());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class OrderItemCreate.", nameof(name));

            if (!count.IsSet)
                throw new ArgumentException("Property is required for class OrderItemCreate.", nameof(count));

            if (!options.IsSet)
                throw new ArgumentException("Property is required for class OrderItemCreate.", nameof(options));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class OrderItemCreate.");

            if (count.IsSet && count.Value == null)
                throw new ArgumentNullException(nameof(count), "Property is not nullable for class OrderItemCreate.");

            if (options.IsSet && options.Value == null)
                throw new ArgumentNullException(nameof(options), "Property is not nullable for class OrderItemCreate.");

            if (primaryAmount.IsSet && primaryAmount.Value == null)
                throw new ArgumentNullException(nameof(primaryAmount), "Property is not nullable for class OrderItemCreate.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class OrderItemCreate.");

            if (discountAmount.IsSet && discountAmount.Value == null)
                throw new ArgumentNullException(nameof(discountAmount), "Property is not nullable for class OrderItemCreate.");

            if (taxAmount.IsSet && taxAmount.Value == null)
                throw new ArgumentNullException(nameof(taxAmount), "Property is not nullable for class OrderItemCreate.");

            if (preparationTime.IsSet && preparationTime.Value == null)
                throw new ArgumentNullException(nameof(preparationTime), "Property is not nullable for class OrderItemCreate.");

            if (weight.IsSet && weight.Value == null)
                throw new ArgumentNullException(nameof(weight), "Property is not nullable for class OrderItemCreate.");

            return new OrderItemCreate(name.Value!, count.Value!.Value!, options.Value!, primaryAmount, amount, discountAmount, taxAmount, imageLink, preparationTime, weight);
        }

        /// <summary>
        /// Serializes a <see cref="OrderItemCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderItemCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrderItemCreate orderItemCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, orderItemCreate, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrderItemCreate" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="orderItemCreate"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrderItemCreate orderItemCreate, JsonSerializerOptions jsonSerializerOptions)
        {
            if (orderItemCreate.Name == null)
                throw new ArgumentNullException(nameof(orderItemCreate.Name), "Property is required for class OrderItemCreate.");

            if (orderItemCreate.Options == null)
                throw new ArgumentNullException(nameof(orderItemCreate.Options), "Property is required for class OrderItemCreate.");

            writer.WriteString("name", orderItemCreate.Name);

            writer.WriteNumber("count", orderItemCreate.Count);

            writer.WritePropertyName("options");
            JsonSerializer.Serialize(writer, orderItemCreate.Options, jsonSerializerOptions);
            if (orderItemCreate.PrimaryAmountOption.IsSet)
                writer.WriteNumber("primary_amount", orderItemCreate.PrimaryAmountOption.Value!.Value);

            if (orderItemCreate.AmountOption.IsSet)
                writer.WriteNumber("amount", orderItemCreate.AmountOption.Value!.Value);

            if (orderItemCreate.DiscountAmountOption.IsSet)
                writer.WriteNumber("discount_amount", orderItemCreate.DiscountAmountOption.Value!.Value);

            if (orderItemCreate.TaxAmountOption.IsSet)
                writer.WriteNumber("tax_amount", orderItemCreate.TaxAmountOption.Value!.Value);

            if (orderItemCreate.ImageLinkOption.IsSet)
                if (orderItemCreate.ImageLinkOption.Value != null)
                    writer.WriteString("image_link", orderItemCreate.ImageLink);
                else
                    writer.WriteNull("image_link");

            if (orderItemCreate.PreparationTimeOption.IsSet)
                writer.WriteNumber("preparation_time", orderItemCreate.PreparationTimeOption.Value!.Value);

            if (orderItemCreate.WeightOption.IsSet)
                writer.WriteNumber("weight", orderItemCreate.WeightOption.Value!.Value);
        }
    }
}
