// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// PaginatedOrderDetailList
    /// </summary>
    public partial class PaginatedOrderDetailList : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaginatedOrderDetailList" /> class.
        /// </summary>
        /// <param name="results">results</param>
        /// <param name="next">next</param>
        /// <param name="previous">previous</param>
        [JsonConstructor]
        public PaginatedOrderDetailList(List<OrderDetail> results, Option<string?> next = default, Option<string?> previous = default)
        {
            Results = results;
            NextOption = next;
            PreviousOption = previous;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [JsonPropertyName("results")]
        public List<OrderDetail> Results { get; set; }

        /// <summary>
        /// Used to track the state of Next
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NextOption { get; private set; }

        /// <summary>
        /// Gets or Sets Next
        /// </summary>
        /* <example>http://api.example.org/accounts/?cursor&#x3D;cD00ODY%3D&quot;</example> */
        [JsonPropertyName("next")]
        public string? Next { get { return this.NextOption; } set { this.NextOption = new(value); } }

        /// <summary>
        /// Used to track the state of Previous
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PreviousOption { get; private set; }

        /// <summary>
        /// Gets or Sets Previous
        /// </summary>
        /* <example>http://api.example.org/accounts/?cursor&#x3D;cj0xJnA9NDg3</example> */
        [JsonPropertyName("previous")]
        public string? Previous { get { return this.PreviousOption; } set { this.PreviousOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PaginatedOrderDetailList {\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("  Next: ").Append(Next).Append("\n");
            sb.Append("  Previous: ").Append(Previous).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PaginatedOrderDetailList" />
    /// </summary>
    public class PaginatedOrderDetailListJsonConverter : JsonConverter<PaginatedOrderDetailList>
    {
        /// <summary>
        /// Deserializes json to <see cref="PaginatedOrderDetailList" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PaginatedOrderDetailList Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<OrderDetail>?> results = default;
            Option<string?> next = default;
            Option<string?> previous = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "results":
                            results = new Option<List<OrderDetail>?>(JsonSerializer.Deserialize<List<OrderDetail>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "next":
                            next = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "previous":
                            previous = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!results.IsSet)
                throw new ArgumentException("Property is required for class PaginatedOrderDetailList.", nameof(results));

            if (results.IsSet && results.Value == null)
                throw new ArgumentNullException(nameof(results), "Property is not nullable for class PaginatedOrderDetailList.");

            return new PaginatedOrderDetailList(results.Value!, next, previous);
        }

        /// <summary>
        /// Serializes a <see cref="PaginatedOrderDetailList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginatedOrderDetailList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PaginatedOrderDetailList paginatedOrderDetailList, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, paginatedOrderDetailList, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PaginatedOrderDetailList" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="paginatedOrderDetailList"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PaginatedOrderDetailList paginatedOrderDetailList, JsonSerializerOptions jsonSerializerOptions)
        {
            if (paginatedOrderDetailList.Results == null)
                throw new ArgumentNullException(nameof(paginatedOrderDetailList.Results), "Property is required for class PaginatedOrderDetailList.");

            writer.WritePropertyName("results");
            JsonSerializer.Serialize(writer, paginatedOrderDetailList.Results, jsonSerializerOptions);
            if (paginatedOrderDetailList.NextOption.IsSet)
                if (paginatedOrderDetailList.NextOption.Value != null)
                    writer.WriteString("next", paginatedOrderDetailList.Next);
                else
                    writer.WriteNull("next");

            if (paginatedOrderDetailList.PreviousOption.IsSet)
                if (paginatedOrderDetailList.PreviousOption.Value != null)
                    writer.WriteString("previous", paginatedOrderDetailList.Previous);
                else
                    writer.WriteNull("previous");
        }
    }
}
