// <auto-generated>
/*
 * BWDK API
 *
 * <div dir=\"rtl\" style=\"text-align: right;\">  # مستندات فروشندگان در سرویس خرید با دیجی‌کالا  این پلتفرم برای فروشندگان (مرچنت‌ها) جهت یکپارچه‌سازی خدمات پرداخت و تجارت الکترونیکی با سیستم خرید با دیجی‌کالا. شامل مدیریت سفارشات، ارسال، و احراز هویت فروشندگان است.  </div> 
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using bwdk_sdk.Client;

namespace bwdk_sdk.Model
{
    /// <summary>
    /// Serializer for shipping method details.
    /// </summary>
    public partial class ShippingMethod : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShippingMethod" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">نام روش ارسال</param>
        /// <param name="getShippingTypeDisplay">getShippingTypeDisplay</param>
        /// <param name="shippingTypeDisplay">shippingTypeDisplay</param>
        /// <param name="deliveryTimeDisplay">deliveryTimeDisplay</param>
        /// <param name="deliveryTimeRangeDisplay">deliveryTimeRangeDisplay</param>
        /// <param name="inventoryAddress">inventoryAddress</param>
        /// <param name="description">توضیحات روش ارسال و جزئیات تحویل آن</param>
        /// <param name="shippingType">نوع روش ارسال: عادی یا دیجی اکسپرس  * &#x60;1&#x60; - سایر * &#x60;2&#x60; - دیجی اکسپرس</param>
        /// <param name="cost">هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان</param>
        /// <param name="secondaryCost">هزینه ارسال برای مناطق دیگر به تومان</param>
        /// <param name="minimumTimeSending">حداقل تعداد روزها از تاریخ سفارش تا تحویل</param>
        /// <param name="maximumTimeSending">حداکثر تعداد روزها از تاریخ سفارش تا تحویل</param>
        /// <param name="isPayAtDestination">Whether the shipping method is pay at destination</param>
        [JsonConstructor]
        public ShippingMethod(int id, string name, string getShippingTypeDisplay, string shippingTypeDisplay, string deliveryTimeDisplay, DeliveryTimeRangeDisplay deliveryTimeRangeDisplay, BusinessAddress inventoryAddress, Option<string?> description = default, Option<ShippingTypeEnum?> shippingType = default, Option<int?> cost = default, Option<int?> secondaryCost = default, Option<int?> minimumTimeSending = default, Option<int?> maximumTimeSending = default, Option<bool?> isPayAtDestination = default)
        {
            Id = id;
            Name = name;
            GetShippingTypeDisplay = getShippingTypeDisplay;
            ShippingTypeDisplay = shippingTypeDisplay;
            DeliveryTimeDisplay = deliveryTimeDisplay;
            DeliveryTimeRangeDisplay = deliveryTimeRangeDisplay;
            InventoryAddress = inventoryAddress;
            DescriptionOption = description;
            ShippingTypeOption = shippingType;
            CostOption = cost;
            SecondaryCostOption = secondaryCost;
            MinimumTimeSendingOption = minimumTimeSending;
            MaximumTimeSendingOption = maximumTimeSending;
            IsPayAtDestinationOption = isPayAtDestination;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ShippingType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<ShippingTypeEnum?> ShippingTypeOption { get; private set; }

        /// <summary>
        /// نوع روش ارسال: عادی یا دیجی اکسپرس  * &#x60;1&#x60; - سایر * &#x60;2&#x60; - دیجی اکسپرس
        /// </summary>
        /// <value>نوع روش ارسال: عادی یا دیجی اکسپرس  * &#x60;1&#x60; - سایر * &#x60;2&#x60; - دیجی اکسپرس</value>
        [JsonPropertyName("shipping_type")]
        public ShippingTypeEnum? ShippingType { get { return this.ShippingTypeOption.Value; } set { this.ShippingTypeOption = new(value); } }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int Id { get; }

        /// <summary>
        /// نام روش ارسال
        /// </summary>
        /// <value>نام روش ارسال</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets GetShippingTypeDisplay
        /// </summary>
        [JsonPropertyName("get_shipping_type_display")]
        public string GetShippingTypeDisplay { get; }

        /// <summary>
        /// Gets or Sets ShippingTypeDisplay
        /// </summary>
        [JsonPropertyName("shipping_type_display")]
        public string ShippingTypeDisplay { get; }

        /// <summary>
        /// Gets or Sets DeliveryTimeDisplay
        /// </summary>
        [JsonPropertyName("delivery_time_display")]
        public string DeliveryTimeDisplay { get; }

        /// <summary>
        /// Gets or Sets DeliveryTimeRangeDisplay
        /// </summary>
        [JsonPropertyName("delivery_time_range_display")]
        public DeliveryTimeRangeDisplay DeliveryTimeRangeDisplay { get; }

        /// <summary>
        /// Gets or Sets InventoryAddress
        /// </summary>
        [JsonPropertyName("inventory_address")]
        public BusinessAddress InventoryAddress { get; }

        /// <summary>
        /// Used to track the state of Description
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> DescriptionOption { get; private set; }

        /// <summary>
        /// توضیحات روش ارسال و جزئیات تحویل آن
        /// </summary>
        /// <value>توضیحات روش ارسال و جزئیات تحویل آن</value>
        [JsonPropertyName("description")]
        public string? Description { get { return this.DescriptionOption; } set { this.DescriptionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Cost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CostOption { get; private set; }

        /// <summary>
        /// هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان
        /// </summary>
        /// <value>هزینه ارسال برای منطقه اولیه (مثلاً تهران) به تومان</value>
        [JsonPropertyName("cost")]
        public int? Cost { get { return this.CostOption; } set { this.CostOption = new(value); } }

        /// <summary>
        /// Used to track the state of SecondaryCost
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SecondaryCostOption { get; private set; }

        /// <summary>
        /// هزینه ارسال برای مناطق دیگر به تومان
        /// </summary>
        /// <value>هزینه ارسال برای مناطق دیگر به تومان</value>
        [JsonPropertyName("secondary_cost")]
        public int? SecondaryCost { get { return this.SecondaryCostOption; } set { this.SecondaryCostOption = new(value); } }

        /// <summary>
        /// Used to track the state of MinimumTimeSending
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MinimumTimeSendingOption { get; private set; }

        /// <summary>
        /// حداقل تعداد روزها از تاریخ سفارش تا تحویل
        /// </summary>
        /// <value>حداقل تعداد روزها از تاریخ سفارش تا تحویل</value>
        [JsonPropertyName("minimum_time_sending")]
        public int? MinimumTimeSending { get { return this.MinimumTimeSendingOption; } set { this.MinimumTimeSendingOption = new(value); } }

        /// <summary>
        /// Used to track the state of MaximumTimeSending
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> MaximumTimeSendingOption { get; private set; }

        /// <summary>
        /// حداکثر تعداد روزها از تاریخ سفارش تا تحویل
        /// </summary>
        /// <value>حداکثر تعداد روزها از تاریخ سفارش تا تحویل</value>
        [JsonPropertyName("maximum_time_sending")]
        public int? MaximumTimeSending { get { return this.MaximumTimeSendingOption; } set { this.MaximumTimeSendingOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsPayAtDestination
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsPayAtDestinationOption { get; private set; }

        /// <summary>
        /// Whether the shipping method is pay at destination
        /// </summary>
        /// <value>Whether the shipping method is pay at destination</value>
        [JsonPropertyName("is_pay_at_destination")]
        public bool? IsPayAtDestination { get { return this.IsPayAtDestinationOption; } set { this.IsPayAtDestinationOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShippingMethod {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  GetShippingTypeDisplay: ").Append(GetShippingTypeDisplay).Append("\n");
            sb.Append("  ShippingTypeDisplay: ").Append(ShippingTypeDisplay).Append("\n");
            sb.Append("  DeliveryTimeDisplay: ").Append(DeliveryTimeDisplay).Append("\n");
            sb.Append("  DeliveryTimeRangeDisplay: ").Append(DeliveryTimeRangeDisplay).Append("\n");
            sb.Append("  InventoryAddress: ").Append(InventoryAddress).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  ShippingType: ").Append(ShippingType).Append("\n");
            sb.Append("  Cost: ").Append(Cost).Append("\n");
            sb.Append("  SecondaryCost: ").Append(SecondaryCost).Append("\n");
            sb.Append("  MinimumTimeSending: ").Append(MinimumTimeSending).Append("\n");
            sb.Append("  MaximumTimeSending: ").Append(MaximumTimeSending).Append("\n");
            sb.Append("  IsPayAtDestination: ").Append(IsPayAtDestination).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Name, length must be less than 64.", new [] { "Name" });
            }

            // Cost (int) maximum
            if (this.CostOption.IsSet && this.CostOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for Cost, must be a value less than or equal to 2147483647.", new [] { "Cost" });
            }

            // Cost (int) minimum
            if (this.CostOption.IsSet && this.CostOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for Cost, must be a value greater than or equal to 0.", new [] { "Cost" });
            }

            // SecondaryCost (int) maximum
            if (this.SecondaryCostOption.IsSet && this.SecondaryCostOption.Value > (int)2147483647)
            {
                yield return new ValidationResult("Invalid value for SecondaryCost, must be a value less than or equal to 2147483647.", new [] { "SecondaryCost" });
            }

            // SecondaryCost (int) minimum
            if (this.SecondaryCostOption.IsSet && this.SecondaryCostOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for SecondaryCost, must be a value greater than or equal to 0.", new [] { "SecondaryCost" });
            }

            // MinimumTimeSending (int) maximum
            if (this.MinimumTimeSendingOption.IsSet && this.MinimumTimeSendingOption.Value > (int)32767)
            {
                yield return new ValidationResult("Invalid value for MinimumTimeSending, must be a value less than or equal to 32767.", new [] { "MinimumTimeSending" });
            }

            // MinimumTimeSending (int) minimum
            if (this.MinimumTimeSendingOption.IsSet && this.MinimumTimeSendingOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for MinimumTimeSending, must be a value greater than or equal to 0.", new [] { "MinimumTimeSending" });
            }

            // MaximumTimeSending (int) maximum
            if (this.MaximumTimeSendingOption.IsSet && this.MaximumTimeSendingOption.Value > (int)32767)
            {
                yield return new ValidationResult("Invalid value for MaximumTimeSending, must be a value less than or equal to 32767.", new [] { "MaximumTimeSending" });
            }

            // MaximumTimeSending (int) minimum
            if (this.MaximumTimeSendingOption.IsSet && this.MaximumTimeSendingOption.Value < (int)0)
            {
                yield return new ValidationResult("Invalid value for MaximumTimeSending, must be a value greater than or equal to 0.", new [] { "MaximumTimeSending" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ShippingMethod" />
    /// </summary>
    public class ShippingMethodJsonConverter : JsonConverter<ShippingMethod>
    {
        /// <summary>
        /// Deserializes json to <see cref="ShippingMethod" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ShippingMethod Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> name = default;
            Option<string?> getShippingTypeDisplay = default;
            Option<string?> shippingTypeDisplay = default;
            Option<string?> deliveryTimeDisplay = default;
            Option<DeliveryTimeRangeDisplay?> deliveryTimeRangeDisplay = default;
            Option<BusinessAddress?> inventoryAddress = default;
            Option<string?> description = default;
            Option<ShippingTypeEnum?> shippingType = default;
            Option<int?> cost = default;
            Option<int?> secondaryCost = default;
            Option<int?> minimumTimeSending = default;
            Option<int?> maximumTimeSending = default;
            Option<bool?> isPayAtDestination = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            id = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "get_shipping_type_display":
                            getShippingTypeDisplay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "shipping_type_display":
                            shippingTypeDisplay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "delivery_time_display":
                            deliveryTimeDisplay = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "delivery_time_range_display":
                            deliveryTimeRangeDisplay = new Option<DeliveryTimeRangeDisplay?>(JsonSerializer.Deserialize<DeliveryTimeRangeDisplay>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "inventory_address":
                            inventoryAddress = new Option<BusinessAddress?>(JsonSerializer.Deserialize<BusinessAddress>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "description":
                            description = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "shipping_type":
                            string? shippingTypeRawValue = utf8JsonReader.GetString();
                            if (shippingTypeRawValue != null)
                                shippingType = new Option<ShippingTypeEnum?>(ShippingTypeEnumValueConverter.FromStringOrDefault(shippingTypeRawValue));
                            break;
                        case "cost":
                            cost = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "secondary_cost":
                            secondaryCost = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "minimum_time_sending":
                            minimumTimeSending = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "maximum_time_sending":
                            maximumTimeSending = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "is_pay_at_destination":
                            isPayAtDestination = new Option<bool?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (bool?)null : utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(name));

            if (!getShippingTypeDisplay.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(getShippingTypeDisplay));

            if (!shippingTypeDisplay.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(shippingTypeDisplay));

            if (!deliveryTimeDisplay.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(deliveryTimeDisplay));

            if (!deliveryTimeRangeDisplay.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(deliveryTimeRangeDisplay));

            if (!inventoryAddress.IsSet)
                throw new ArgumentException("Property is required for class ShippingMethod.", nameof(inventoryAddress));

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class ShippingMethod.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class ShippingMethod.");

            if (getShippingTypeDisplay.IsSet && getShippingTypeDisplay.Value == null)
                throw new ArgumentNullException(nameof(getShippingTypeDisplay), "Property is not nullable for class ShippingMethod.");

            if (shippingTypeDisplay.IsSet && shippingTypeDisplay.Value == null)
                throw new ArgumentNullException(nameof(shippingTypeDisplay), "Property is not nullable for class ShippingMethod.");

            if (deliveryTimeDisplay.IsSet && deliveryTimeDisplay.Value == null)
                throw new ArgumentNullException(nameof(deliveryTimeDisplay), "Property is not nullable for class ShippingMethod.");

            if (deliveryTimeRangeDisplay.IsSet && deliveryTimeRangeDisplay.Value == null)
                throw new ArgumentNullException(nameof(deliveryTimeRangeDisplay), "Property is not nullable for class ShippingMethod.");

            if (inventoryAddress.IsSet && inventoryAddress.Value == null)
                throw new ArgumentNullException(nameof(inventoryAddress), "Property is not nullable for class ShippingMethod.");

            if (description.IsSet && description.Value == null)
                throw new ArgumentNullException(nameof(description), "Property is not nullable for class ShippingMethod.");

            if (shippingType.IsSet && shippingType.Value == null)
                throw new ArgumentNullException(nameof(shippingType), "Property is not nullable for class ShippingMethod.");

            if (cost.IsSet && cost.Value == null)
                throw new ArgumentNullException(nameof(cost), "Property is not nullable for class ShippingMethod.");

            if (secondaryCost.IsSet && secondaryCost.Value == null)
                throw new ArgumentNullException(nameof(secondaryCost), "Property is not nullable for class ShippingMethod.");

            if (minimumTimeSending.IsSet && minimumTimeSending.Value == null)
                throw new ArgumentNullException(nameof(minimumTimeSending), "Property is not nullable for class ShippingMethod.");

            if (maximumTimeSending.IsSet && maximumTimeSending.Value == null)
                throw new ArgumentNullException(nameof(maximumTimeSending), "Property is not nullable for class ShippingMethod.");

            if (isPayAtDestination.IsSet && isPayAtDestination.Value == null)
                throw new ArgumentNullException(nameof(isPayAtDestination), "Property is not nullable for class ShippingMethod.");

            return new ShippingMethod(id.Value!.Value!, name.Value!, getShippingTypeDisplay.Value!, shippingTypeDisplay.Value!, deliveryTimeDisplay.Value!, deliveryTimeRangeDisplay.Value!, inventoryAddress.Value!, description, shippingType, cost, secondaryCost, minimumTimeSending, maximumTimeSending, isPayAtDestination);
        }

        /// <summary>
        /// Serializes a <see cref="ShippingMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shippingMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ShippingMethod shippingMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, shippingMethod, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ShippingMethod" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="shippingMethod"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ShippingMethod shippingMethod, JsonSerializerOptions jsonSerializerOptions)
        {
            if (shippingMethod.Name == null)
                throw new ArgumentNullException(nameof(shippingMethod.Name), "Property is required for class ShippingMethod.");

            if (shippingMethod.GetShippingTypeDisplay == null)
                throw new ArgumentNullException(nameof(shippingMethod.GetShippingTypeDisplay), "Property is required for class ShippingMethod.");

            if (shippingMethod.ShippingTypeDisplay == null)
                throw new ArgumentNullException(nameof(shippingMethod.ShippingTypeDisplay), "Property is required for class ShippingMethod.");

            if (shippingMethod.DeliveryTimeDisplay == null)
                throw new ArgumentNullException(nameof(shippingMethod.DeliveryTimeDisplay), "Property is required for class ShippingMethod.");

            if (shippingMethod.DeliveryTimeRangeDisplay == null)
                throw new ArgumentNullException(nameof(shippingMethod.DeliveryTimeRangeDisplay), "Property is required for class ShippingMethod.");

            if (shippingMethod.InventoryAddress == null)
                throw new ArgumentNullException(nameof(shippingMethod.InventoryAddress), "Property is required for class ShippingMethod.");

            if (shippingMethod.DescriptionOption.IsSet && shippingMethod.Description == null)
                throw new ArgumentNullException(nameof(shippingMethod.Description), "Property is required for class ShippingMethod.");

            writer.WriteNumber("id", shippingMethod.Id);

            writer.WriteString("name", shippingMethod.Name);

            writer.WriteString("get_shipping_type_display", shippingMethod.GetShippingTypeDisplay);

            writer.WriteString("shipping_type_display", shippingMethod.ShippingTypeDisplay);

            writer.WriteString("delivery_time_display", shippingMethod.DeliveryTimeDisplay);

            writer.WritePropertyName("delivery_time_range_display");
            JsonSerializer.Serialize(writer, shippingMethod.DeliveryTimeRangeDisplay, jsonSerializerOptions);
            writer.WritePropertyName("inventory_address");
            JsonSerializer.Serialize(writer, shippingMethod.InventoryAddress, jsonSerializerOptions);
            if (shippingMethod.DescriptionOption.IsSet)
                writer.WriteString("description", shippingMethod.Description);

            if (shippingMethod.ShippingTypeOption.IsSet)
            {
                var shippingTypeRawValue = ShippingTypeEnumValueConverter.ToJsonValue(shippingMethod.ShippingType!.Value);
                writer.WriteNumber("shipping_type", shippingTypeRawValue);
            }
            if (shippingMethod.CostOption.IsSet)
                writer.WriteNumber("cost", shippingMethod.CostOption.Value!.Value);

            if (shippingMethod.SecondaryCostOption.IsSet)
                writer.WriteNumber("secondary_cost", shippingMethod.SecondaryCostOption.Value!.Value);

            if (shippingMethod.MinimumTimeSendingOption.IsSet)
                writer.WriteNumber("minimum_time_sending", shippingMethod.MinimumTimeSendingOption.Value!.Value);

            if (shippingMethod.MaximumTimeSendingOption.IsSet)
                writer.WriteNumber("maximum_time_sending", shippingMethod.MaximumTimeSendingOption.Value!.Value);

            if (shippingMethod.IsPayAtDestinationOption.IsSet)
                writer.WriteBoolean("is_pay_at_destination", shippingMethod.IsPayAtDestinationOption.Value!.Value);
        }
    }
}
